### ISSUE TITLE
Implement separate features needing admin rights.

### ISSUE THREAD

**Issue by OpenSourceCS** [MaxXor/xRAT#100]
While I looked back all the feature requests, i thought some of these feature requests need admin rights. What about Implementing all these features, making a try catch and if the feature requests for admin rights and if the client denies, send a packet to server saying that the command failed.
Especially the issue #81 is superb.

 
#88 is dormant.
I beg you all to read all my issues and feature requests. Some of them may be really useful.

BTW this is the :100:  th issue.

The wiki of this repo remains unupdated

**Comment by DragonzMaster** [comment]
this is not an issue as you can simply look at Account Type and see if it is "Admin" so you can do these stuff if it is other"User" so you can't
it is easy and don't need all what you demand

**Comment by OpenSourceCS** [comment]
I just asked about implementing features involving admin rights

**Comment by yankejustin** [comment]
The command would fail anyway if the user was not an administrator (and it needed to be). The command <b>should</b> already result in such a response.

**Comment by MaxXor** [comment]
The wiki is not updated because I have not much time for it. :100:
