### ISSUE TITLE
Reverse Socks5 Proxy

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#103]
I was looking at project's main page
and found under ToDo:
Socks5 Proxy

so can i suggest a project would help us to achieve this
Project's Name: Socks5
https://github.com/ThrDev/Socks5
It is stable but it is normal Proxy and need little changes to be Reverse Proxy
so if anyone like the idea go with it and try
If no one likes it just close the issue

**Comment by yankejustin** [comment]
I agree with this. While I truthfully still am rather new to Reverse Proxies, I still do believe that we should use ThrDev's project. :+1:

**Comment by electriclee** [comment]
why reversee |{use direct}

**Comment by AnguisCaptor** [comment]
I'm pretty good in this kinda stuff, have done Reverse Proxies / Socks4/5/HTTPS proxies in the past, will see what I can do with this :)

**Comment by DragonzMaster** [comment]
We will not forget that favor hahaha :laughing:  @AnguisCaptor 
it will be prety thing and so cool that we bring reverse proxy to like such project

**Comment by AnguisCaptor** [comment]
Created a pull request https://github.com/MaxXor/xRAT/pull/113
So far the proxy server for HTTPS / Socks5 seems to be working

Enjoy :)

**Comment by d3agle** [comment]
@AnguisCaptor, youre the best

**Comment by DragonzMaster** [comment]
your are awesome guy @AnguisCaptor 
Really Great Job

**Comment by AnguisCaptor** [comment]
Haha thanks :D
I am planning to change more in the Reverse Proxy ;)
You'll see it soon enough :)

**Comment by bitterypaul** [comment]
I  am ashamed to ask this but please someone tell me what is reverse proxy and what is the use of it. Btw great and biggest commit @AnguisCaptor

**Comment by yankejustin** [comment]
@bitterypaul It is a normal connection, but literally in reverse. It follows a different flow model to where, instead of it going from client to server (client sends request and server handles it), it goes from server to client (server sends a request and client handles it). Please correct me if I am wrong. :)

**Comment by bitterypaul** [comment]
tysm @yankejustin, what is the use of it.

**Comment by AnguisCaptor** [comment]
@bitterypaul thanks :), the purpose for Reverse Proxy is simple: use the Internet of your target/victim
A normal proxy socks5 or HTTPS requires portforwarding, but the target/victim in the RAT will most likely not portforward so we need something more clever, we will run the Socks5/HTTPS proxy server and connect to localhost (our proxy server) and sending all the connection requests to the victim/target, that way we're able to use the victims/target's internet

**Comment by bitterypaul** [comment]
thank you @AngiusCaptor and @yankejustin you are all my technical gods.

**Comment by bitterypaul** [comment]
ok then , will it saitsfy issue #71

**Comment by AnguisCaptor** [comment]
As promised, some cool updates :)
https://github.com/MaxXor/xRAT/pull/140 - Kill connections
https://github.com/MaxXor/xRAT/pull/141 - A Proxy Load Balancer, DNS hostname resolver

**Comment by DragonzMaster** [comment]
@AnguisCaptor next update should add authorization using user/pass with the ability to change them without disconnecting the server ... it would be useful

**Comment by DragonzMaster** [comment]
@AnguisCaptor another problem appeared minutes after starting the server the client closes
and proxifier shows "Infinite Connection Loop Detection"

**Comment by AnguisCaptor** [comment]
@DragonzMaster I had the same issue earlier when using Proxifier, you need to add a rule in proxifier
Use the following settings:
Name: Ignore port 3128
Target Port: 3128
Action: Direct

The problem with proxifier is that it's a system wide proxy, so that it will even try to proxy a proxy in this case lol
So we need to tell proxifier to ignore our proxy server

**Comment by DragonzMaster** [comment]
@AnguisCaptor  so you need to force stopping the proxy server(server side) and closing reverse form in case of crashing client and make the client restart
