### ISSUE TITLE
Quasar connection issues.

### ISSUE THREAD

**Issue by JoshySimps** [MaxXor/xRAT#1134]
I had some of my friend willingly test the quasar build and none of them were able to connect even after turning off all AC features.
The ip address is the same and the port is the same but still nothing seems to happen. I tried with different mutex and different build settings but I can't figure out what is going on. is there something I'm missing? any help is appreciated

**Comment by MaxXor** [comment]
Please use the issue template. Please check the getting started page in wiki: https://github.com/quasar/Quasar/wiki/Getting-Started#6-connecting-the-server-and-client

Especially part 4 and 6.
