### ISSUE TITLE
Remote Webcam?

### ISSUE THREAD

**Issue by Krytox** [MaxXor/xRAT#120]
I am not sure if this has been asked already but are there any chances for the webcam func in the later stages of the software?

**Comment by yankejustin** [comment]
I doubt it, unless MaxXor is willing to add another library to handle it. Things like webcam and microphone functionality are incredibly low-level and are rather complex. It would be far too time-consuming to re-invent the wheel and make this ourselves.

**Comment by yankejustin** [comment]
@MaxXor This can be closed. In later stages, perhaps. However, the complexity of this feature (especially in C#) exceeds the complexity of xRAT... In short, it would be a very <b>major</b> addition.
