### ISSUE TITLE
Remove lock (_lockClients)

### ISSUE THREAD

**Issue by nil-ref** [MaxXor/xRAT#1215]
### Problem description

Can "lock (_lockClients)" be omitted because it is always in the UI thread and called by lstClients.Invoke.

### Proposal

Remove lock (_lockClients)

**Comment by MaxXor** [comment]
When two clients connect simultaneously it needs to be ensured via the lock that the clients list is only modified one at a time (same for disconnects). But there may be better ways to handle this. Currently it is not safe to remove it.
