### ISSUE TITLE
How do i use reverse proxy?

### ISSUE THREAD

**Issue by CherryWerryWoods** [MaxXor/xRAT#1216]
### Problem description

Hello i had a question i want to know how i can use reverse proxy, do i need to setup a new port and connection or is there something else i need to do?

### Proposal

Someone tell me how do i use it

**Comment by MaxXor** [comment]
You have to enter "localhost" as host and the chosen port in your browser settings, e.g. https://support.mozilla.org/en-US/kb/connection-settings-firefox (SOCKS5 proxy)

This way you can use the internet connection of the client to browse the web.
