### ISSUE TITLE
Add Microphone + Camera

### ISSUE THREAD

**Issue by 0x32-l3git** [MaxXor/xRAT#1220]
### Problem description

When I install Quasar onto a windows machine for Redteam use, I always have to use shell to install another program for microphone and camera.

### Proposal

A Camera and Microphone feature being built in Quasar natively will be very useful. This should be easy to implement and other forks have done this, but these tend to be buggy and I cannot use this when it is unstable.

**Comment by edcdecl** [comment]
microphone + camera were removed and they probably aren't going to be added back. please use the search function on github to look at previous issues, since this question has been asked several times before.
