### ISSUE TITLE
Not receiving any connections from clients

### ISSUE THREAD

**Issue by trxwick** [MaxXor/xRAT#1229]
I know that this is a duplicate issue, but I have looked around the issues page, and the issue itself, and nothing so far has helped. Everything seems to be correct but I cant get a single connection?
![Builder](https://github.com/quasar/Quasar/assets/98618925/43a124cf-6175-4fdb-b58e-7a048d72eac5)
![Settings](https://github.com/quasar/Quasar/assets/98618925/170f2942-05fb-4593-bb2f-94d5120ff906)

**Comment by SSIDSpin** [comment]
Also got this issue, if you fix it please lmk asap

**Comment by TimSchallmayer** [comment]
I also got this issue
