### ISSUE TITLE
Sending text from client form to server throws exception

### ISSUE THREAD

**Issue by Knakiri** [MaxXor/xRAT#1235]
FormRemoteChat.cs
![image](https://github.com/quasar/Quasar/assets/95192545/25d083ff-f3c1-4e99-a277-aa9a5b385170)
RemoteChatHandler.cs
![image](https://github.com/quasar/Quasar/assets/95192545/bc155cf3-2cf1-4530-819f-4dd5d20eff35)

what am i doing wrong here?

**Comment by Knakiri** [comment]
i suspect its because something related to ISender but still couldnt figure it out

**Comment by MaxXor** [comment]
Check out the simplest form of a message, the show messagebox feature: https://github.com/search?q=repo%3Aquasar%2FQuasar+DoShowMessageBox&type=code

**Comment by Knakiri** [comment]
> Check out the simplest form of a message, the show messagebox feature: https://github.com/search?q=repo%3Aquasar%2FQuasar+DoShowMessageBox&type=code

I know your sending from server request to execute the messagebox but what if you dont want a request from server first? I am working on remote chat but when client is trying to send text to server it throws null exception
