### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by DoginGG** [MaxXor/xRAT#1240]
Hi, I disabled the firewall, turned off the antivirus, opened ports, set up port map,no-ip, even though I put all of this as hosts to builder and my client still can not connect when connected to a different network.

I also checked if my laptop can ping my computer while connected to another network and it can that's why Im making this post bc I searched there for any solution and in Reddit, google, etc and I don't know what's wrong. It is not my 1st time connecting with my computer outside the network, I know can do that but somehow Quasar can't do that :/

**Comment by DoginGG** [comment]
That was fast can I know why?

**Comment by MaxXor** [comment]
Please check out the Getting Started guide, especially the part at the bottom: https://github.com/quasar/Quasar/wiki/Getting-Started

**Comment by DoginGG** [comment]
Done at start

**Comment by MaxXor** [comment]
What does https://portchecker.co/ say? You need to use the same public IP and port in the client builder.

**Comment by DoginGG** [comment]
![obraz_2024-01-24_202352904](https://github.com/quasar/Quasar/assets/130414092/6b3ed80a-9544-4b07-94bd-19eb168cdf02)

port opened

**Comment by DoginGG** [comment]
so thats the problem

**Comment by DoginGG** [comment]
I just made minecraft server and everything is working fine, so its must be Quasar

**Comment by DoginGG** [comment]
@MaxXor any ideas?
