### ISSUE TITLE
I cant connect client with host

### ISSUE THREAD

**Issue by TimSchallmayer** [MaxXor/xRAT#1242]
### Quasar version

1.4.1

### Server operating system

Windows 11/Server 2022

### Client operating system

Windows 11/Server 2022

### Build configuration

Debug

### Describe the bug

I and my friend have setup the client on his pc and the host on my but it does not work

### How to reproduce

.

### Expected behavior

.

### Actual behavior

.

### Additional context

.

**Comment by edcdecl** [comment]
Check out the Getting Started guide: https://github.com/quasar/Quasar/wiki/Getting-Started

**Comment by TimSchallmayer** [comment]
thank you
