### ISSUE TITLE
Linux port for Quasar.exe (not the client)

### ISSUE THREAD

**Issue by BOplaid** [MaxXor/xRAT#1248]
### Problem description

I want to run the quasar server from a VM, but the only VM that I have is Linux Mint and I don't have enough storage for a Windows VM.

### Proposal

I want to be able to run Quasar.exe from Linux.

### Additional context

P.S. How is Quasar pronounced? everyone says it in a different way.

**Comment by MaxXor** [comment]
Hi, you can try running Quasar server with Mono (.NET) on Wine, see this issue: https://github.com/quasar/Quasar/issues/1116
[It is planned to make the server work on Linux platform](https://github.com/quasar/Quasar/issues/774), but the UI needs to be rewritten (e.g. as web application) which is a lot of work.

Quasar is pronounced like this (English): https://translate.google.com/;?sl=auto&tl=en&text=Quasar&op=translate
