### ISSUE TITLE
Bug: stopping listen server

### ISSUE THREAD

**Issue by d3agle** [MaxXor/xRAT#125]
Stopping the listen server with multiple clients connected will not correctly disconnect the client/remove from listview

**Comment by yankejustin** [comment]
Will it remove the clients correctly and just not update the interface as it should, or is it not disconnecting them correctly entirely?

**Comment by d3agle** [comment]
Both

**Comment by yankejustin** [comment]
lol... got it! I will look into it.

**Comment by d3agle** [comment]
I didn't get a chance to debug it, but stopping the listen server, one of the clients would still be in the listview, and would respond to commands.  It appeared that only one of the clients would hang left over.  I tested this first with 2 active clients, then 3 active clients

**Comment by yankejustin** [comment]
Interesting. Any exceptions thrown?

**Comment by d3agle** [comment]
I believe so yes.  Set a breakpoint on Disconnect method in xServer.Core.Server.  I believe the problem lies within the logic in that method, although I'm not sure
