### ISSUE TITLE
Please enter a valid file version number!

### ISSUE THREAD

**Issue by ju4ka1371** [MaxXor/xRAT#1255]
### Quasar version

1.4.1

### Server operating system

Windows 11/Server 2022

### Client operating system

Windows 11/Server 2022

### Build configuration

Debug

### Describe the bug

When I try to change the “assembly settings”, namely “product version”, when I try to build, I get an error: Please enter a valid file version number!

No matter what I write there, this error appears

### How to reproduce

change the “assembly settings”, namely “product version”

### Expected behavior

Building

### Actual behavior

Build failed

**Comment by MaxXor** [comment]
It literally says that the version information needs to be in format "1.2.3.4". What do you enter?

**Comment by ju4ka1371** [comment]
> It literally says that the version information needs to be in format "1.2.3.4". What do you enter?

I also tried "1.2.3.4". Not so stupid)

Just solved the problem. I put the folder with the program in the root of the "c" drive and everything worked

**Comment by MaxXor** [comment]
Weird, okay. Did your path to Quasar.exe contain any special characters at the previous location?

**Comment by ju4ka1371** [comment]
> Weird, okay. Did your path to Quasar.exe contain any special characters at the previous location?

Launched from the desktop directory. From the folder "Quasar v1.4.1". There are no special characters, spaces or signs in the username. English letters only
