### ISSUE TITLE
Enhancement: Remote desktop - Keyboard input

### ISSUE THREAD

**Issue by d3agle** [MaxXor/xRAT#126]
Adding the ability to send keyboard input to the remote client via remote desktop.

Managing remote clients can be a bit difficult without the ability to use send keyboard input to the client machine.  Having to create an application to set specific text to the clipboard to be able to have input on the client machine can be a bit annoying

**Comment by bitterypaul** [comment]
superb idea

**Comment by DragonzMaster** [comment]
i was just going to open an issue about that
and it will be more reliable to send multiple keys like [alt+ctrl+del] or  [alt+tab] ........
