### ISSUE TITLE
Upgrade to .NET Framework 3.5

### ISSUE THREAD

**Issue by tidusjar** [MaxXor/xRAT#128]
This is a question:
Just wondering why we do not upgrade the .NET version? With 2.0 we cannot make use of any good asynchronous tasks? Multithreading is a lot more difficult and cumbersome in 2.0...

**Comment by bitterypaul** [comment]
We can safely change the build config to target .NET 4.0 without breaking compatibility with Windows XP

**Comment by tidusjar** [comment]
@bitterypaul I think it would be a good solution then we can use the more recent things in the .NET framework.

**Comment by DragonzMaster** [comment]
that's to make the project compatible with most of OS
if we upgrade it to 3.5 (as an example) we won't be sure that it would work on most of Win XP as many of them uses 2.0

**Comment by tidusjar** [comment]
@DragonzMaster I'm not questioning anyone here but if Microsoft don't support Win XP, should we? I can see a lot of benefit to upgrade the .NET version.

**Comment by yankejustin** [comment]
@bitterypaul Of course. The .NET framework version has no reason to break compatibility with Windows XP.

**Comment by yankejustin** [comment]
@DragonzMaster These days, most machines (even the few running Windows XP for some reason) should at least have v3.5

**Comment by yankejustin** [comment]
I would agree with @tidusjar ... 3.5 is huge enough. Each version has an immense amount of wonderful changes to simplify and improve code.

**Comment by DragonzMaster** [comment]
i know that win xp is the only one which come with 2.0 instead of 3.5 with came with win vista and newer
anyway you can do what you want

**Comment by tidusjar** [comment]
@MaxXor what is you opinion on this?

**Comment by MaxXor** [comment]
I believe it's okay if we change the target framework to 3.5. :)

I will do this later.

**Comment by yankejustin** [comment]
Wonderful. :)

**Comment by yankejustin** [comment]
@MaxXor Would you please create a new branch for upgrading the framework to 3.5? There are many places I see that would benefit greatly from the new features offered by v3.5

Also, would you consider changing the following code signature for invoking?:
<code>Invoke((MethodInvoker)delegate { });</code>
to something like this:
<code>Invoke(() => { });</code>
<hr />
I just would like to add that the two empty parenthesis can be more clear because it can contain parameters, and empty parenthesis would show others that there are no parameters. :)

**Comment by MaxXor** [comment]
@yankejustin 
Yes, I'll do this. :)

Uhm, I think it's not that important, or? :confused:

**Comment by yankejustin** [comment]
It is not that important. It is more of a preference. :)

**Comment by MaxXor** [comment]
Upgrade is done, you can now start using more powerful methods from the .NET Framework 3.5 CP.
