### ISSUE TITLE
Common classes

### ISSUE THREAD

**Issue by tidusjar** [MaxXor/xRAT#130]
Hi,

I have a question why we are duplicating work?
There seems to be a few 'common' classes in the solution where they are duplicated in both projects. e.g. encryption. Why do we not have a 'Common' Project with these classes in that the other projects just reference?

**Comment by MaxXor** [comment]
I want the client to have no dependencies except the default ones from the .net framework.

**Comment by tidusjar** [comment]
Why can't we have a dependency on our own controlled, small library? I'm just thinking it would help out with the project structure and maintainability.

**Comment by yankejustin** [comment]
@MaxXor I think you may have misunderstood @tidusjar
If I am understanding correctly, tidusjar is suggesting that we move code that is the same for the server and the client (for example: protobuf) to another project and have the server and use the same project so we don't have to make a change to the server or client, then reflect the change to the other project. Doing this would mean we only have to change one and it would be unnecessary to require a duplicate change in the other project.

**Comment by tidusjar** [comment]
@yankejustin Correct. We would then only make the change in one location and it would be consistent across the server and client. But it would require 1 more .DLL

**Comment by MaxXor** [comment]
@tidusjar and I don't allow this one more DLL, sorry.

**Comment by rabbitsmith** [comment]
@MaxXor i think this is feasible.we can use ilmerge to combine the protobuf dll , encryption dll and client.exe after compiling them. simply search in google for ilmerge.exe.

**Comment by rabbitsmith** [comment]
we can merge mono.cecil with xrat.exe
