### ISSUE TITLE
Remote Shell

### ISSUE THREAD

**Issue by madified** [MaxXor/xRAT#14]
It is indeed a great effort. There's just a little bug. On server end remote shell is displaying 2nd last response instead of latest one.

**Comment by MaxXor** [comment]
Can you tell me the steps to reproduce this issue? I don't have this on my test machine.

**Comment by madified** [comment]
No idea how to fix it.. I was working on keylogger.. Finally built a stable and virus clean keylogger for xRAT but after you 2nd last commit xRAT client is unstable. (Right after client execution process stops. Please Check.)

**Comment by MaxXor** [comment]
Can you please download the latest source again and build it. Check if the problem still occurs and try to step through the source with the debugger to find out where the problem occurs.
