### ISSUE TITLE
gitter

### ISSUE THREAD

**Issue by bitterypaul** [MaxXor/xRAT#144]
please set up gitter so that people can talk about feature requests and bugs separate from the github issues. thanks a million

**Comment by MaxXor** [comment]
I don't think this is necessary...

**Comment by yankejustin** [comment]
@MaxXor Sorry for dragging you to a closed issue but would you suppose the best place to ask questions or discuss should be opening issues?

**Comment by MaxXor** [comment]
At the moment the issues on github are enough. And who should answer all the questions on gitter, I guess there will be more than issues?

**Comment by rabbitsmith** [comment]
@bitterypaul your choice of wordings is wrong. @MaxXor we can setup gitter for discussing about next priority instead of cluttering issues such as in issue #149

**Comment by rabbitsmith** [comment]
@yankejustin my humble request. i cant understand what you mean. sorry because english isnt my first language

**Comment by rabbitsmith** [comment]
@MaxXor awaiting your reply

**Comment by yankejustin** [comment]
@MaxXor Do you suppose we could use this now? It would be nice to discuss a few ideas. :)
It would also help remove many of the issues we currently have open.

**Comment by MaxXor** [comment]
Added it now. :) You can visit it here: https://gitter.im/MaxXor/xRAT

**Comment by yankejustin** [comment]
Thank you. It is appreciated. :)
