### ISSUE TITLE
Client Gone Unstable

### ISSUE THREAD

**Issue by madified** [MaxXor/xRAT#15]
I checked multiple commits, and client-built is totally unstable after commit "Optimized Server Start | e325a78e2313a113270d2374f205b6b5a887ae58". Infact client-built don't even starts on Windows 8.1 Pro and Windows XP sp3.

**Comment by MaxXor** [comment]
To use the in-built builder please build the solution in RELEASE mode and not DEBUG mode.
Please check this.

**Comment by madified** [comment]
I know that i'm using release mode in VS 2012 Ultimate.

**Comment by MaxXor** [comment]
So, you build both projects in release mode and then start the server to build the client, correct?

**Comment by madified** [comment]
Yea. and i tried all these commits.

Stable
Changed README.md 82839f6c8771adc2e2a935abfba4aed0fbf469d3  
Added version to builder as argument 9a329711a7a8c21a5be9cb342aaf8bfb3706d642
Optimized Server Start e325a78e2313a113270d2374f205b6b5a887ae58

Unstable
Refactored namespace    e3ad2f07163750dae0d2af533acf8f9c38d4f320
Refactored class access modifiers   2544f3a230b91fe1499a23f465fcaf2d524614a9
Fixed #14    55de07401ff7a51e2aca6c532a66e76371094f94
Close RemoteShell window on exit  3ba3a10b139a25bfd280d7a2c0d9904be5418bb6

**Comment by madified** [comment]
I Built a keylogger+autoUSBspread+Startup+ReportMailing almost a year back. Now simplified it just to keylogging, to add in xRAT but not sure at which point should I create & start Keylogger Thread.

Should I send you the Keylogger Class to add in.?

**Comment by MaxXor** [comment]
Sorry, corrected the namespaces now. You were right, while I was renaming all namespaces I forgot to change the builder, now it finds the correct namespaces while building the client.

How would you implement your Keylogger Class? :) Just call it somewhere where you think it's good and then create a pull request. Thanks!

**Comment by madified** [comment]
Worked like a charm .. (y)

**Comment by madified** [comment]
Except remote shell :(

![screenshot 188](https://cloud.githubusercontent.com/assets/8765809/5764923/668e692a-9d17-11e4-8f5b-87db3cc665fa.png)
