### ISSUE TITLE
Client crashes when Stop Listening on server

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#153]
As shown in the title
When the client is running and i stop listening (Server) the client crash
Client.exe has Stopped Working
So anyone else faces this problem ?

**Comment by MaxXor** [comment]
Working fine for me here. I can stop and start listening and the client connects again.

**Comment by DragonzMaster** [comment]
hmmmm it is really strange
i tried again and the client still crashes

**Comment by d3agle** [comment]
Yes it is doing it for me as well.  I will investigate.  This is with the most recent master-branch

**Comment by MaxXor** [comment]
Start the client in debug mode and the Server normally. Then reproduce the crash and the Debugger will stop at the exception. Plesse tell me as much as Visual Studio tells you, like name, line number. :)

**Comment by d3agle** [comment]
@MaxXor, I first started the client normally by building it, stopping the listen server the client crashed.  It doesn't crash in debug however

**Comment by DragonzMaster** [comment]
no the debug mode the client work smoothly and never crash
it seems that the problem with release mode :thought_balloon:

**Comment by d3agle** [comment]
It is throwing a System.TypeLoadException.  Probably something in the Servers renamer class

**Comment by DragonzMaster** [comment]
i remember that the renamer caused a problem with the previous Keylogger also
so can it be the problem like what @d3agle said ??

**Comment by d3agle** [comment]
This is the error message I'm getting in Visual studio 2015:

System.TypeLoadException was unhandled
Message: An unhandled exception of type 'System.TypeLoadException' occurred in Client-built.exe
Additional information: Method 'Dispose' in type '䬖從晃쯓ⰷ샡躥䇆뎿﷤㕵ด瓐㙏䈁៫䢫쯻' from assembly 'Client, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by d3agle** [comment]
Is there any way to exclude obfuscating types that implement the IDisposable interface?

**Comment by d3agle** [comment]
Sent a pull request #154 for this fix

**Comment by DragonzMaster** [comment]
i hope it fixed the problem @d3agle

**Comment by DragonzMaster** [comment]
@MaxXor  please can we make the renamer optional ??

**Comment by yankejustin** [comment]
@DragonzMaster To clarify, do you mean that it crashes before deletion and does not create the batch file that deletes itself?

**Comment by DragonzMaster** [comment]
no it crashes and ("client.exe has stopped working) appears then it is deleted @yankejustin

**Comment by yankejustin** [comment]
@DragonzMaster Try it again and see if it still does that. :)

**Comment by DragonzMaster** [comment]
It seems that both of the 2 fixes do work 
not one of them alone as i had to fix both of the renemer and the shell to get the problem fixed

**Comment by yankejustin** [comment]
So both fixes fix both of your issues?

**Comment by DragonzMaster** [comment]
yes :smiley: 
I tried again with @d3agle fix only and it seems to fix both issues (sorry i didn't notice that)
and i think the try-catch block you made won't hurt  :laughing:  
thanks for both of you ... good work

**Comment by yankejustin** [comment]
Yeah you're right. ;)
If the process was already terminating the client would discontinue working as described above. It would not even be able to uninstall correctly. :poultry_leg:
