### ISSUE TITLE
Remote Shell Messed UP

### ISSUE THREAD

**Issue by madified** [MaxXor/xRAT#16]
Checked almost everything. Uptill now everything works fine except remote shell.
{u may revert back shell to previous state} 

PFA screen shot.
![screenshot 188](https://cloud.githubusercontent.com/assets/8765809/5765099/9e6f85d0-9d18-11e4-9cd3-b5f6de279d66.png)

**Comment by MaxXor** [comment]
Hehe, yes the remote shell is a mess. But this behavior is not normal, it didn't happen on my computer. I'll check it tomorrow and see what I can do. Thanks!
