### ISSUE TITLE
Mutex Murder

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#170]
<h1>Background</h1>
The mutex prevents multiple instances of the client in an effective way, allowing simple termination of any additional clients that are (attempted to be) initialized under the same mutex.

<h1>Behavior Expected</h1>
1. Client user initializes a client program.
2. Client user attempts to initialize an additional client program though one client program has already been initialized under the same mutex.
3. Client user's additional client programs do not initialize; since one is already running, the additional client programs kill themselves.

<h1>Actual Behavior</h1>
1. Client user initializes a client program.
2. Client user attempts to initialize an additional client program though one client program has already been initialized under the same mutex.
3. Client user's additional client programs do not initialize; since one is already running, the additional client programs kill themselves.
4. <i><b>ISSUE</b></i>&nbsp;&nbsp;&nbsp;  <b>Client user's first client stops working (with a popup of the Windows message indicating a crashed application).</b>

**Comment by MaxXor** [comment]
Again, the client application does not crash in Release mode, using the same mutex when one client is already installed.

**Comment by yankejustin** [comment]
I will investigate these two issues tonight and see why my client is doing this. I will re-open if I still experience issues and will inform you of any irregularities.

**Comment by rabbitsmith** [comment]
was the problem solved.
