### ISSUE TITLE
Client does not correctly uninstall

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#171]
<h1>Behavior Expected</h1>
1. Client is connected to the server.
2. Server issues a command to the client to uninstall itself.
3. Client removes file entries, logs, registry keys, etc.
4. Client creates a batch file to execute to remove the executable.
5. Client uninstalls completely by executing the batch file to terminate the program and remove the executable.
6. Client is gone

<h1>Actual Behavior</h1>
1. Client is connected to the server.
2. Server issues a command to the client to uninstall itself.
3. <b>Client application crashes (with a popup message from Windows indicating an application crash).</b>

**Comment by MaxXor** [comment]
I can't confirm any of the two issues you've created. Tested both in Debug and Release mode, lol.

It worked before, so why doesn't it work now for you?

**Comment by yankejustin** [comment]
I will investigate these two issues tonight and see why my client is doing this. I will re-open if I still experience issues and will inform you of any irregularities.

**Comment by rabbitsmith** [comment]
was the problem solved
