### ISSUE TITLE
New Keylogger Window Titles which contain Arabic chars show incorrectly

### ISSUE THREAD

**Issue by d3agle** [MaxXor/xRAT#180]
Opening this issue from my fork

@DragonzMaster @MaxXor

**Comment by d3agle** [comment]
@DragonzMaster , are you still having this problem? If so, does it happen with all of arabic text in window titles, or specific characters?

**Comment by DragonzMaster** [comment]
No More Problems
Thanks Guys
![kel3](https://cloud.githubusercontent.com/assets/12255107/7785214/a2601868-0185-11e5-8276-c9c7d3cb10b0.png)

**Comment by d3agle** [comment]
Awesome!
