### ISSUE TITLE
Code Improvement in Builder

### ISSUE THREAD

**Issue by ModdersCentral** [MaxXor/xRAT#185]
private bool StringNotNull(string() strs){
   for(int i=0;i<strs.length;i++){
   if (string.IsNullOrEmpty(txtHost.Textstrs(i))) return false;
   }
   return true;
   }

or

private bool NotNull(object() strs){
   for(int i=0;i<strs.length;i++){

switch(strs.type){
case String://for strings
   if (string.IsNullOrEmpty(strs(i))) return false;
break;
case Bool: //for checkbox
 if (strs(i)) return false;
break;
}

   }
   return true;
   }

https://github.com/MaxXor/xRAT/blob/master/Server/Forms/FrmBuilder.cs
line 246

Also you may want to use linq to make it even shorter.

**Comment by ModdersCentral** [comment]
Maybe replace this

asmInfo = new string[8];
                            asmInfo[0] = txtProductName.Text;
                            asmInfo[1] = txtDescription.Text
                            asmInfo[2] = txtCompanyName.Text;
                            asmInfo[3] = txtCopyright.Text;
                            asmInfo[4] = txtTrademarks.Text;
                            asmInfo[5] = txtOriginalFilename.Text;
                            asmInfo[6] = txtProductVersion.Text;
                            asmInfo[7] = txtFileVersion.Text;


with this:


asmInfo = new string[7] {txtProductName.Text,txtDescription.Text,txtCopyright.Text,txtTrademarks.Text,txtOriginalFilename.Text,txtProductVersion.Text,txtFileVersion.Text};

**Comment by ModdersCentral** [comment]
Maybe then replace this:

txtInstallname.Enabled = chkInstall.Checked;
            rbAppdata.Enabled = chkInstall.Checked;
            rbProgramFiles.Enabled = chkInstall.Checked;
            rbSystem.Enabled = chkInstall.Checked;
            txtInstallsub.Enabled = chkInstall.Checked;
            chkHide.Enabled = chkInstall.Checked;
            chkStartup.Enabled = chkInstall.Checked;

with this:


for each (Control o  in ((object )(ctrls1 { txtInstallname,rbAppdata, rbProgramFiles,   rbSystem,   txtInstallsub, chkHide, chkStartup}))){
o.Enabled = chkInstall.Checked;
}

**Comment by yankejustin** [comment]
That is very difficult to read... Though it is shorter, it would take a significantly larger amount of effort to go through and make sense of what we are looking at. It is also useful to stay consistent with the rest of the project...
I would also suggest making a pull request for things like this next time, too. :)

**Comment by yankejustin** [comment]
@MaxXor This can be closed. Changes like this should probably be made into a pull request, or should  be in a discussion style arguing the style to use for the program. :)
