### ISSUE TITLE
[Keylogger] Handle Modifier key AltGr correctly

### ISSUE THREAD

**Issue by MaxXor** [MaxXor/xRAT#194]
When pressing `AltGr + 2` it shows `[Control + Alt + D2]`, correct behaviour would be `²`.
If your keyboard doesn't have an AltGr key, you can also use `Control + Alt` for this.

**Comment by d3agle** [comment]
I will keep looking into this.  From what I've read, and experimented with, this might not be a feasible fix, but I won't give up!

**Comment by d3agle** [comment]
This explains what I have experimented with.
![](http://puu.sh/hZKAc/138f1acbb1.png)


The differences between the two keypresses resulted in the following, on my system with a german keyboard layout (non german keyboard):
![](http://puu.sh/hZKE0/a03c405a3e.png)

There might be some way to hack this together to detect if the last two KeyDown keys are equivalent to the AltGr input data, as it differs from a control + alt keydown, but this might get messy fast.  I'll play around with it and see what I can come up with.
