### ISSUE TITLE
Client-builder not saving settings

### ISSUE THREAD

**Issue by d3agle** [MaxXor/xRAT#197]
not sure why this happened, but I noticed it after trying to build a client with new settings (it didn't prompt me to save my settings)

**Comment by d3agle** [comment]
not sure why this happened, but I noticed it after trying to build a client with new settings (it didn't prompt me to save my settings)

to reproduce: 
delete Bin/Release/Profiles/Default.xml
delete Bin/Release/settings.xml

Start server listen
Build client with new settings
(No prompt to save settings?)

**Comment by yankejustin** [comment]
I will deal with this. The settings manager should implement <code>INotifyPropertyChanged</code> eventually. :)

**Comment by d3agle** [comment]
@yankejustin, :+1: sounds good.

Just a little note: changed a setting 'disabled keylogger' and saved the settings, then it prompted me to save settings..  I'm going to assume its a check for a/some setting(s) that doesn't trigger saving the file unless the settings are different than the ones read from the file
