### ISSUE TITLE
Corrupted File Message

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#20]
Issue where, when the client closes unexpectedly - often either shutting down the machine or closing via the server's command - the client cannot open the issue due to a Windows message popping up that states that there are 4 corrupted files in "C:\Users\*MyUserName*\Documents". Screenshot will be posted soon.

**Comment by MaxXor** [comment]
Can you tell me which options you have used while building your client?

This window with the corrupted files comes from the Admin elevation trick.

**Comment by yankejustin** [comment]
Options used to build client:
IP/Hostname: My IP
Port:4782
Password: 1234
Reconnect Delay: 5000 ms
Mutex: SjIIz4NsyJLQyHUBhUkGOwN88PRjFvHS
Install Client: FALSE
Enable Admin Elevation: TRUE
Change Icon: FALSE

However, even when I close the open client and rebuild everything, and even if I do NOT have "Enable Admin Elevation" checked when I build a new client and run it, the message will persist.
How should I find the corrupted files?

**Comment by MaxXor** [comment]
Delete all stuff from the old client first (be sure to kill the process), then rebuild it with Admin Elevation set to `false`. Please read this: https://github.com/MaxXor/xRAT#compiling

**Comment by yankejustin** [comment]
I dug a bit deeper and realized that I had forgotten to delete a few hanging files. I will see if it works very soon. I will test if it works as it did yesterday on my main machine and I will report the results as soon as I can.

**Comment by yankejustin** [comment]
As for now, the client is no longer causing Windows to bark at me about corrupted files. :)

**Comment by MaxXor** [comment]
Alright, good to know it's working for you!
