### ISSUE TITLE
file manager bug

### ISSUE THREAD

**Issue by rabbitsmith** [MaxXor/xRAT#200]
i tried to download torbrowser to the downloads folder using file manager . I right clicked and selected download. originally the file was in d drive. Before transfer the installer was working . After the transfer the installer shows error.

**Comment by MaxXor** [comment]
Are you using the a binary compiled from the latest source code or RELEASE3?

**Comment by rabbitsmith** [comment]
i use the compiled master branch in release mode

**Comment by rabbitsmith** [comment]
please use any file greater than 30 mb to reproduce the issue

**Comment by MaxXor** [comment]
Downloaded a 70mb file over File Manager and compared the file hashs, they were equal. Means the files are identical.

**Comment by MaxXor** [comment]
Please compile from latest source code and try again.

**Comment by rabbitsmith** [comment]
i tried the latest source code. everything else works fine except this

**Comment by MaxXor** [comment]
Can you compare the hashs of the two files if they are identical?

**Comment by rabbitsmith** [comment]
torbrowser uses nsis. it checks for integrity of files before installation. i already checked the hashes and it does not match. the file sizes are slightly different. after transferring the installer is 257kb smaller than the original, working installer.

**Comment by rabbitsmith** [comment]
i tried connecting to localhost using xrat to the latest compiled client.exe from master branch running on the same pc. the problem still persists. everything else is fine

**Comment by MaxXor** [comment]
Why does it work for me, please send me your compiled binaries and I'll test with it.

**Comment by rabbitsmith** [comment]
i am truly sorry but i couldnt upload the binaries . i use github on a java phone in a 2g network. i compiled xrat using the latest source code in release mode. my phone uplink is stuck somewhere at 400b/s

**Comment by MaxXor** [comment]
Can you do it when you're at your computer? :)

**Comment by rabbitsmith** [comment]
maybe the problem is with the os. i use windows 10 technical preview which my friend gave me. the build version is 9879

**Comment by MaxXor** [comment]
Good that you mention this, I'll test xRAT asap on Windows 10. :) Hasn't been tested yet on W10.

**Comment by rabbitsmith** [comment]
i have utmost issues connecting my java phone to my pc to connect my pc to the internet. i dont have broadband.

**Comment by rabbitsmith** [comment]
i have the torbrowser in the root of the d drive. i tried transferring it within lan to another pc with w10 . i also tried the same with xrat connected to localhost

**Comment by rabbitsmith** [comment]
i also tried the binaries from appveyor. the problem still persists within lan also on localhost

**Comment by rabbitsmith** [comment]
keylogger is working as expected in release mode. i tried all keys and some combinations and it works perfect

**Comment by MaxXor** [comment]
Thanks, good to know! :) I'm going to test xRAT on Windows 10 now.

**Comment by rabbitsmith** [comment]
keylogger is working as expected in release mode. i tried all keys and some combinations and it works perfect in windows 10

**Comment by MaxXor** [comment]
Downloaded latest xRAT from appveyor on Windows 10, transferred tor browser and compared the hashs, they are equal... :( Still can't reproduce this issue.

![File Transfer](https://i.imgur.com/1T5sQo1.png)

**Comment by rabbitsmith** [comment]
i found that upload and executing torbrowser installer works fine. when i download torbrowser from a client over lan multiple times the sizes differ each time
