### ISSUE TITLE
get google chrome history

### ISSUE THREAD

**Issue by rabbitsmith** [MaxXor/xRAT#203]
if anybody finds this useless, just comment and i will close it. a feature to get google chrome history would be useful. same is the case with other browsers. see this article for more details 

http://stackoverflow.com/questions/2562092/how-to-access-google-chrome-browser-history-programmatically-on-local-machine

**Comment by MaxXor** [comment]
I don't think this is needed.

**Comment by rabbitsmith** [comment]
we plan to implement password stealer but why not this

**Comment by d3agle** [comment]
I think LaPanthere might have the code for this already, or for decrypting the sql3 .db and accessing the information.

Also I think it would be more suitable to change the name of 'password stealer' to something more non-chalant, perhaps 'password recovery' xD

**Comment by d3agle** [comment]
lol nvm just realized it was already renamed xD
