### ISSUE TITLE
using ilmerge to combine dependencies

### ISSUE THREAD

**Issue by rabbitsmith** [MaxXor/xRAT#204]
i am interested to know whether we could use ilmerge.exe to combine mono.cecil and other libraries (not client.bin and client.exe) with xrat.exe si that we can get a minimized number of dependencies. could be useful to implement needs of issue #130

**Comment by MaxXor** [comment]
This is not useful for xRAT.exe, but more for the client.

**Comment by rabbitsmith** [comment]
so can we reopen issue #130?

**Comment by yankejustin** [comment]
This does not minimize the number of dependencies. In essence, we still would be dependent on external libraries that we have little control of. This would have the unfortunate side-effect of making things more difficult.

**Comment by rabbitsmith** [comment]
fortunately we can create separate projects for common classes like protobuf and encryption.

**Comment by MaxXor** [comment]
No.
