### ISSUE TITLE
Update from local file bug

### ISSUE THREAD

**Issue by d3agle** [MaxXor/xRAT#205]
To reproduce - build Client, set install path etc.., build another client after installing the first client, then update.  I think the batch file is not able to move the client if names are the same

**Comment by d3agle** [comment]
If names are different, it will copy the new file, but if names are same it wont.

Also, it does not delete the original (first) client

**Comment by MaxXor** [comment]
No idea what you are doing wrong, tried what you said and it worked. What names do you mean, the file name specified in the Builder for the install location or the file name after building the client?

Can you please tell me the exact steps to reproduce this.

**Comment by d3agle** [comment]
Yeah sure, sorry!

Ok, so the first test:
Build client (No install path), put it on Desktop of VM (Make sure to put it in a certain spot so you will notice if it deletes, and moves the new client to another spot -I don't know if auto-arrange matters here).  Execute client on VM.  Build another client with the exact same name, update from file, launch.  The first client on your desktop should delete and be moved to a new location. (I don't know if this matters but I changed mutex, shouldn't matter because the first client will be out of memory by the time the new one is launched)

Second test:
Build client (With install path, and preferably different name for testing purposes), make the registry name noticeable, something like "123".  Execute the client on VM.  Opening start up manager you will notice the registry name "123".  

Build another client with same install path and same install name.  This time make the registry name "1234" to notice the change. Update client from file.

For me this did not work, however, when using the install path when building the client and changing the name of the executable (internal) when it is installed and copied to the specified location, that the update from file did work.

I think what is happening is the batch file may not be able to delete the file

**Comment by d3agle** [comment]
OR if the names are the same, it will try to move the new file to the same install directory, and the old file is not deleted yet so it cannot move the file when it renames it to the same name as the old file

**Comment by d3agle** [comment]
Ok, so this is not a bug with the update from file.

This is a bug somewhere else, I think in the profiles saving settings!

I put some code in to show a message box from the new client.  It showed the messagebox upon executing, however I changed the registry name with this new file, and it did not show it changed in either msconfig or startup manager.  I think the settings are not saving

**Comment by d3agle** [comment]
Going to close this, followed the debug for builder and everything seems to be working fine now.  It is weird that it would act this way (not changing registry names after executing)

**Comment by d3agle** [comment]
@MaxXor , after further investigation, the reason it isn't deleting the registry is because we are disconnecting the file instead of uninstalling! ;D
