### ISSUE TITLE
Registry Editor Icon

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#217]
@MaxXor I would greatly appreciate it if you would please add an icon on the main form for the Registry Editor. :)

**Comment by DragonzMaster** [comment]
Can I suggest this ?
https://thecustomizewindows.com/wp-content/uploads/2010/11/regedit-icon.png

**Comment by yankejustin** [comment]
@DragonzMaster Please don't blatantly disregard their <b><a href="https://thecustomizewindows.com/copyright-policy/">copyright policy</a></b>...

**Comment by DragonzMaster** [comment]
I am really sorry @yankejustin  
I deleted the comment

**Comment by yankejustin** [comment]
I'll delete mine, too. Just please always be respectful of others' intellectual property. :large_blue_circle:

**Comment by DragonzMaster** [comment]
I forgot this ... it was my fault

**Comment by yankejustin** [comment]
Thank you!
