### ISSUE TITLE
Multiple icons in the icons menu

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#218]
<h1>Issue Description</h1>
After initializing the xRAT server and closing the main form in a way besides the [X] button, the icon remains (as visible in <b>Figure 1</b>). This is often a common issue with many programs, but perhaps it can be fixed for xRAT. :)

<h4>Reference</h4>
<b><a href="https://github.com/MaxXor/xRAT/blob/master/Server/Forms/FrmMain.cs#L186">This line</a></b> is never hit when closing abnormally, causing a visible leftover NotifyIcon.

<br />
<hr />
<br />
<h4>Figure 1</h4>
![116c13ce30409103d03d67408a5bfcfa](https://cloud.githubusercontent.com/assets/9338742/7827930/ff282a5a-03fa-11e5-8f94-699084ae447d.jpg)

**Comment by MaxXor** [comment]
This is a common problem when the application gets closed unexpectedly, but this shouldn't be the case in normal use of xRAT.

See: https://social.msdn.microsoft.com/Forums/windows/en-US/73c33537-c5d7-4cff-9faa-0a6a0d4a65b4/notifyicon-icon-still-visible-after-closing-form?forum=winforms

**Comment by yankejustin** [comment]
Thank you for the reference.
