### ISSUE TITLE
Remote Desktop Mouse & Keyboard Support

### ISSUE THREAD

**Issue by d3agle** [MaxXor/xRAT#219]
I think it would be helpful to have more functionality as far as mouse input goes.  Currently we are only able to click/double click/right click.  If we want to move a window to somewhere else on the screen we aren't able to drag the window to another location.  Also, if there are a cluster of files we are wanting to highlight, it becomes a difficult and overwhelming task.  This would also make a great addition to when LaPanthere finishes keyboard input :)

If this is something acceptable, I can have this added shortly.  (Already have the logic implemented in an older build)

**Comment by yankejustin** [comment]
<h1>Related Issues:</h1>
1. <b><a href="https://github.com/MaxXor/xRAT/issues/126">Issue 126</a></b>
    - Keyboard input from the remote desktop and remote combinations handling.
2. <b><a href="https://github.com/MaxXor/xRAT/issues/112">Issue 112</a></b>
    - Mouse input from the remote desktop to the client.

**Comment by d3agle** [comment]
@MaxXor, Do you think this is acceptable?  I can implement this easily.

My idea behind this is to make the Remote Desktop feature similar to something like TeamViewer (as far as mouse input goes)

**Comment by MaxXor** [comment]
Yes, we should improve the Remote Desktop to make it more user friendly and bug-free. :)

**Comment by d3agle** [comment]
Great :D I will improve the mouse interaction for now, and will likely focus on the keyboard part this upcoming week.

**Comment by d3agle** [comment]
#299

**Comment by d3agle** [comment]
Will also implement Delta handling (MWHEEL) :D
