### ISSUE TITLE
file manager enhancements

### ISSUE THREAD

**Issue by rabbitsmith** [MaxXor/xRAT#224]
a feature to move, copy files within the client's computer and features to eject and displaying properties of files, showing transfer speeds in transfers tab, opening a folder by pressing enter key, feature to search for a specified file or folder, making refresh option as an icon instead of a right click menu, upload here, compute hash(rarely used,optional), etc

**Comment by MaxXor** [comment]
Why do you reference 227 everywhere?? Stop that.

**Comment by yankejustin** [comment]
About half of these features have already been suggested and are open (awaiting implementation by whichever contributor that wants to implement it).
Could you possibly revise this issue and remove features already suggested please? Also, remember Github supports most HTML tags, so you could use (un)ordered lists to make multiple requests easier to address.
<b><a href="https://help.github.com/articles/github-flavored-markdown/">Reference</a></b>
