### ISSUE TITLE
remote desktop bug- does not respond after ctrl alt del

### ISSUE THREAD

**Issue by rabbitsmith** [MaxXor/xRAT#225]
if we press ctrl alt delete while the remote desktop session is started and then escape key is pressed, remote desktop window in xrat.exe does not respond. no input can be sent to client and then the picture does not update even after stopping and starting the remote desktop session. the only way to get it to work again is to close the remote desktop window and opening it again.

**Comment by d3agle** [comment]
O_o, just tried this and it kills my client, it just crashes

**Comment by d3agle** [comment]
fixed

**Comment by yankejustin** [comment]
Hold on. I re-wrote some of it.

**Comment by yankejustin** [comment]
This way, the client will continue attempting to use Remote Desktop while it is still active, even if something happens in between transfer (likely the client can't correctly handle it correctly).

**Comment by d3agle** [comment]
@yankejustin, yeah, its because graphics.copyfromscreen cant find the handle when the ctrl + alt+ delete screen is open, throwing a win32exception

**Comment by yankejustin** [comment]
Yeah I know. I just didn't realize at first what the ctrl+alt+delete screen does to the operating system.

**Comment by d3agle** [comment]
Perhaps there is some alternatives to graphics.copyfromscreen?  I don't think a try catch block would affect performance too much, or would it?

**Comment by yankejustin** [comment]
Think of it this way: performance is not comparable when the output is not right. If try-catch blocks aren't there, we can't say it is more efficient or works faster because it will <b>not</b> be the right end result. An end result that is not correct is infinitely slower in my eyes.

**Comment by yankejustin** [comment]
As for try-catch blocks, it ends up being almost the exact same speed. If an exception is thrown, it is a tiny bit slow, but it is desirable thing to have 1/2 a millisecond of performance hits at max instead of a crashed application. :)
I have tested try-catch blocks and there is no difference.

**Comment by d3agle** [comment]
That makes sense!  I couldn't notice a visible performance hit either :P

**Comment by yankejustin** [comment]
As a reference, the reason we do not surround <i>every method</i>  in try-catch blocks is because it is important to handle the exceptions <b>in the correct spot</b>. Otherwise, behavior is not enforced, GUIs are not set to the correct state, and the upset client gets frustrated. :)
