### ISSUE TITLE
cant find client....

### ISSUE THREAD

**Issue by itapi** [MaxXor/xRAT#233]
hey bro.. first of all i would like to say ur job is amazing as i could so from the features :)

i've compiled the server but than i tried to set the client as startup project and debug it too but it just notworking... nothing appears... o.O

**Comment by yankejustin** [comment]
You need to right-click on the "Client" project and press "Rebuild". After that, start the <b>"Server"</b> project. Use the "Server" project to build the client executable file, then run the client executable file that was generated. :)

<b>Additional Reference:</b>
<b><a href="https://github.com/MaxXor/xRAT#building-a-client">Building Clients</a></b>

**Comment by yankejustin** [comment]
@itapi If you need more help I can message you a few more details to get it running. Just e-mail me at: yankejustin@hotmail.com

**Comment by yankejustin** [comment]
@MaxXor This can be closed. Haven't heard a response, and the comments above should be enough help to get it running. :)
