### ISSUE TITLE
reverse proxy clarification

### ISSUE THREAD

**Issue by rabbitsmith** [MaxXor/xRAT#235]
sorry for making noise but i really couldnt understand what reverse proxy does. please could someone explain this elaborately. thanks.

**Comment by yankejustin** [comment]
As much as I personally dislike not giving a direct answer, please understand I hate to type the exact same thing (usually applies well in code too... hehe)
Read the comments in <b><a href="https://github.com/MaxXor/xRAT/issues/103">this issue</a></b>.
