### ISSUE TITLE
MessageBox Enchancement

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#236]
Limit the length of the text that is allowed to be placed in the "Show Messagebox" command on the server side to prevent extremely large message boxes (they can't be closed by the client and it is annoying).
On the client side, truncate any text outside of a range around 256 characters or so.

**Comment by MaxXor** [comment]
Server side limitation is enough I think. :)

**Comment by yankejustin** [comment]
Sounds good.
