### ISSUE TITLE
Question about Merging Upstream

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#237]
<h4>Preceding Note</h4>
I normally don't post questions that are not directly relevant to xRAT, but I feel it is important to ask you, MaxXor, since this is a bit of an issue for me regarding xRAT contributions (and a few others, I have noticed).
<hr />
<h1>Context</h1>
I have been doing some work on the <code>RegistryEditor</code> branch. Because it is something I contribute that is lower in priority than other things I wish to fix, add, or otherwise change on xRAT, sometimes I find that the branch gets (sometimes <i>very</i>) behind in recent big changes. My usual solution is to send myself a pull request from the <code>MaxXor/master</code> branch to my fork and merge it. I have come to dislike doing so because it will occasionally build up (makes pull requests more ugly), and it can make the history of the <code>MaxXor/master</code> branch a little bit muddy.

<h1>Question</h1>
How should I go about merging upstream a possibly large amount of changes without making a mess of the history?

**Comment by MaxXor** [comment]
It's okay to have merge pull requests from `MaxXor/master` in your history, these merge pull requests will be later ignored anyways. Well, the other way I can think of is backing up your files and re-create the fork, but this can be a lot of work.

**Comment by yankejustin** [comment]
Okay, thank you.
