### ISSUE TITLE
MultiPort Listener [Server Side] & Backup DNS [Client Side]

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#238]
I suggest to add multi-port listener to the server
and each port can have its own PW
We also can add backup DNS TO reduce the case of losing clients

**Comment by rabbitsmith** [comment]
i support this idea.

**Comment by DragonzMaster** [comment]
we will wait to know MaxXor opinion about that

**Comment by MaxXor** [comment]
I already saw this in some other RATs. My question is: Has anyone actually used this? I didn't.

**Comment by DragonzMaster** [comment]
I can understand this
but it will be useful for someone else

**Comment by rabbitsmith** [comment]
what about adding freedns.afraid.org support as it requires only a secret key and does not need username and password for updating

**Comment by yankejustin** [comment]
MultiPort listeners are not possible to implement on a TCP connection...

**Comment by DragonzMaster** [comment]
What I mean Is making the server accept connection from (for Example) 2 clients one of them connecting through Port 4782 and the other connected to port 5782
the second point I mean to add a backup DNS to the Client and if the client can not connect to the primary DNS It will try to connect to Backup DNS @MaxXor 
So how it can be impossible ?? as It is already implemented in other RATs ? @yankejustin

**Comment by yankejustin** [comment]
@DragonzMaster I have looked into it more since my last comment and I just must say... <i>What a mess trying to maintain it</i>. It just is not at all convenient, especially for the difficulty of managing it with the lack of benefits.

**Comment by yankejustin** [comment]
And about <i>"the other RATs"</i> that do <i>this</i> and <i>that</i>, just remember that because other projects have it, we may not have a use for it so it is not implemented.
Instead of comparing xRAT (as I unfortunately see often), please give a little bit of insight as to <b>why</b> some of these things are important to the project and perhaps a little <i>cost (time, effort, etc.)-benefit</i> analysis on it.
Above all, remember you can always implement it yourself. I knew almost nothing about computers and how they function, and I knew nothing about databases, websites, or coding at all only <i>2 years ago</i>.

**Comment by yankejustin** [comment]
As for the back-up DNS, that should be a separate enhancement for itself. I actually think it is useful thing to implement just so a client may know where to go. Perhaps it could be in a drop-down in the Builder Form and can be edited when connected to the server.

**Comment by DragonzMaster** [comment]
Thanks Guys For Your Valuable Time
And I'AM NOT COMPARING IT WITH (ANOTHER RAT) BUT I AM HOPPING TO SEE THIS PROJECT THE BEST EVER
I am SORRY I will Close this untill I finish my exams and see if i can implement it myself as you said @yankejustin

**Comment by yankejustin** [comment]
I'd like it if you would open another issue only for the back-up DNS, though. That is something I am actually going to implement because I dislike relying on one unchangeable one. :)

**Comment by DragonzMaster** [comment]
OK I will do it
