### ISSUE TITLE
Unused event?

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#240]
I am unsure what the <b><a href="https://github.com/MaxXor/xRAT/blob/master/Server/Core/Server.cs#L50">ClientWrite</a></b> event is being used for. It seems as though it isn't used for anything.

**Comment by MaxXor** [comment]
Yes, it's there so we have an event for each action: Write, Read, State. Just for completeness.

**Comment by yankejustin** [comment]
Oh, I see. I excluded documentation for it because of lack of use at the moment. I was just curious, so thank you for the response. :)

**Comment by MaxXor** [comment]
Would you like to add the documentation for the Write event too? :)

**Comment by yankejustin** [comment]
I think you should because it would be much more clear to express the intent.
I'm going to add more documentation to a few large spots tomorrow night. Have a good night. :)

**Comment by MaxXor** [comment]
Ok, you too! :)
