### ISSUE TITLE
Enhancement : Backup DNS [Client]

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#242]
Adding a feature allows to add another DNS (backup DNS) which the client try to connect To in the case of failure to connect through the primary DNS

**Comment by Abdullah2993** [comment]
any recommendations for the DNS provider?

**Comment by DragonzMaster** [comment]
Which DNS Provider ?? @Abdullah2993

**Comment by MaxXor** [comment]
@Abdullah2993 For example this: https://freedns.afraid.org/

I've added the ability to add multiple hosts to the client when you build it. I think that's enough.
