### ISSUE TITLE
Add User@PC Name to main menu ListView and use it in keylogger

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#245]
Hi @MaxXor 
Please, I want to know if there is any problem if we add User Name and PC name to main menu listview like [User@PC-Name] to make it easier to know which client we deal with
And If we can make the folder created in [Clients Folder] will be like User@PC-Name instead of IP as ISP in many countries don't offer static IP so there will be new folder every time the router restarts
I wait for you opinion about that :smile:

**Comment by rabbitsmith** [comment]
this is a very useful feature. i support this.

**Comment by MaxXor** [comment]
Will be added before the release of the next version. :) I want this in the next release.

**Comment by yankejustin** [comment]
Good. Didn't even think about it.

**Comment by d3agle** [comment]
Awesome idea this is very helpful, and will also help to segregate clusters of clients that share the same IP address.
