### ISSUE TITLE
Add more ways to obtain GeoIP information

### ISSUE THREAD

**Issue by d3agle** [MaxXor/xRAT#248]
Would it be possible to add multiple methods to obtaining GeoIP information, or a more reliable way to obtain the information?  There are times where getting the GeoIP information doesn't work very well and the image flag isn't retrieved.  This has been happening often lately.

Also, not sure if this is intended but the country flag is located in the User@PC column.  Should it be located in the IP Address column?

**Comment by MaxXor** [comment]
Fixed the small bug, yes maybe one more. :)

**Comment by d3agle** [comment]
Sounds good, thanks. :)
