### ISSUE TITLE
Port number data type

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#251]
<h1>Change Requested:</h1>
The port number is currently stored as an <code>int</code>. While we currently parse the text from the Settings Form as a <code>ushort</code>, the data type used to store the port number is an <code>int</code>.

**Comment by MaxXor** [comment]
huh? The client and server stores the Port as `ushort` already??
https://github.com/MaxXor/xRAT/blob/master/Server/Core/Server.cs#L15
https://github.com/MaxXor/xRAT/blob/master/Client/Config/Settings.cs#L14

**Comment by yankejustin** [comment]
I apologize. I misread.

**Comment by DavesPlanet** [comment]
@MaxXor part of this proposed change would allow the port number to be configurable, allowing you to recover if you lost your VPN service. The other part would allow for at least one fallback DNS entry for the host, allowing you to recover if you lost your DNS service. I find both of these to be very valuable features.

**Comment by yankejustin** [comment]
@DavesPlanet You may have misunderstood my purpose for opening this issue:
I had misread the data type for the port, mistaking the <code>ushort</code> it correctly uses and instead thought it was an <code>int</code>. There was no issue besides my misunderstanding of what is currently <i>correctly</i> used.

**Comment by DavesPlanet** [comment]
@yankejustin actually I'm just too stoopid to realize this was a discussion of a bug report and not of the pull request. Sorry for my ignorance.
