### ISSUE TITLE
User@PC doesn't show correctly in listview

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#255]
I have faced this problem but I really don't have any idea why this is happening
Anyone else has faced this problem ?
![xrat](https://cloud.githubusercontent.com/assets/12255107/7925362/f35f62ba-08c3-11e5-88d5-96b6560de491.png)

**Comment by DragonzMaster** [comment]
Oh my bad I really sorry i forget to update these Clients
I apologise :smile:

**Comment by MaxXor** [comment]
Strange enough that they even connect and are shown there. :D Usually this doesn't work when you are using a newer server version as the client version.

**Comment by DragonzMaster** [comment]
I was using Commit 591 Before Updating to Commit 601
so maybe there is no much changes applied that affect the connection between Server & Client :smile:

**Comment by yankejustin** [comment]
@MaxXor It hilariously functions both ways. I opened up a server from the second release by accident and it still worked. Not every feature was working 100% with the client, but it still worked. I also have opened up a really old client on a new server. Though the client was very unstable, little has changed in the way the connections are handled to a point where it is surprisingly backwards-compatible. :100:

**Comment by MaxXor** [comment]
Nice. xD
