### ISSUE TITLE
Startup Manger Shows NOTHING

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#256]
I tried to get startup entries but the form opens and shows nothing
I tried with more than one client but still shows nothing
I tried on my PC using "localhost", it worked
anyone else face this problem ??

-------------------------------------------------------------------
EDIT : even after using latest commit (616)
![xr3](https://cloud.githubusercontent.com/assets/12255107/7957679/97ab4034-09e9-11e5-9005-439d36e816aa.png)

**Comment by MaxXor** [comment]
Maybe the PCs don't have any startup entries?

**Comment by DragonzMaster** [comment]
No, I am sure that there are startup entries
I forgot to to mention that the statue of client [server side] is "Startup information failed"

**Comment by MaxXor** [comment]
I see the mistake, the users are probably running the client under normal privileges, not admin right?

The client also tries to get the

**Comment by DragonzMaster** [comment]
no even if the client run under admin privil. the same problem happens
![xrat2](https://cloud.githubusercontent.com/assets/12255107/7929942/e1b65f1a-0903-11e5-87ee-ee18a5c17a66.png)

**Comment by MaxXor** [comment]
ok, I'll see if i can fix this later today. :)

**Comment by DragonzMaster** [comment]
Ok, Thanks in advance. :smile:

**Comment by DragonzMaster** [comment]
@MaxXor  Please, Are you sure that it is working now ??
as it seems that it doesn't work even after using latest commit (615)

**Comment by yankejustin** [comment]
I have tested this and it is working fine for me now. Perhaps this has something to do with you using Windows 8.

**Comment by DragonzMaster** [comment]
Did you test it with your PC or a client (not on your LAN ) ? @yankejustin

**Comment by DragonzMaster** [comment]
the only one who i can get startup entries from @MaxXor 
a small bug appears,  as you see the file located in startup folder but is shown under HKLM/RUN
![xr2](https://cloud.githubusercontent.com/assets/12255107/7951952/718ea250-09ae-11e5-96a6-21875a89eef9.png)

**Comment by MaxXor** [comment]
@yankejustin your count variable fucked it up a bit... :(

**Comment by MaxXor** [comment]
You forgot that there was an IF (https://github.com/MaxXor/xRAT/commit/dc5bef821ee3bb8786bac25cb836a8b846f31ee5#diff-102b515604a387697dd3c8a5c16b8227L106) so it wasn't couting right on 32bit systems.

**Comment by DragonzMaster** [comment]
Please, @MaxXor Can you reopen this issue as I still have this problem.

**Comment by yankejustin** [comment]
Oh, wow. I apologize.

**Comment by DragonzMaster** [comment]
@MaxXor 
Using Commit 618
![x4](https://cloud.githubusercontent.com/assets/12255107/7960404/aa4933ba-0a00-11e5-9386-d65b2f0dbefc.png)

**Comment by MaxXor** [comment]
Thanks, okay try now the latest commit. It should fix this issue.

**Comment by DragonzMaster** [comment]
Oh finally it works good, Thank you very much @MaxXor 
Well Done :+1:  :100:

**Comment by MaxXor** [comment]
No problem!!
