### ISSUE TITLE
Cant detect the client

### ISSUE THREAD

**Issue by lordcedrich** [MaxXor/xRAT#260]
Hi Sir,

I would like ask if the xRAT Release 3 supported the static ip? im just wondering why i cant detect the client on my network and my Server pc ip is 192.168.0.2 and the client is 192.168.0.55.

**Comment by MaxXor** [comment]
Please use the latest version from the master-branch from here: https://ci.appveyor.com/project/MaxXor/xrat

Be sure to have your ports opened.

**Comment by lordcedrich** [comment]
Hi Sir,
Im just wondering if i can download all the master-branch in 1 downloading? I just download the zip files and it seems the codes is not been updated.
 


     On Wednesday, June 3, 2015 1:43 PM, MaxXor <notifications@github.com> wrote:
   

 Please use the latest version from the master-branch from here: https://ci.appveyor.com/project/MaxXor/xratBe sure to have your ports opened.—

**Comment by DragonzMaster** [comment]
Here you can download the source code updated to latest commit
https://github.com/MaxXor/xRAT/archive/master.zip
then unzip it and open (build-release.bat)
