### ISSUE TITLE
Critical Disk Error

### ISSUE THREAD

**Issue by lordcedrich** [MaxXor/xRAT#261]
Hi Sir,

Im encountering an error Critical Disk Error when launching the release client.exe
Im using windows 7 32 bit and all the visual effects has been set to the  adjusted to the best performance. Im using the latest release in branch master

"Multiple corrupted files has been found in the directory 'My documents' , To prevent serious loss of data please allow to restore these files.

Corrupted directory C:\Users \Windows 7 Pro\Documents
Corrupted files count: 4

![Uploading Screenshot_1.jpg…]()

**Comment by DragonzMaster** [comment]
This happen if you only open a client with elevation trick turned on

**Comment by MaxXor** [comment]
Just think about this.

**Comment by lordcedrich** [comment]
so you mean i need to turned it off? but how

**Comment by yankejustin** [comment]
My admin privileges hurt. ;)

Don't worry, we all can get fooled by a trick sometimes. :100:

**Comment by yankejustin** [comment]
<b><a href="https://github.com/MaxXor/xRAT/blob/master/Client/Core/Elevation/FrmElevation.cs#L122">Reference</a></b>

**Comment by MaxXor** [comment]
@yankejustin feel free to correct it. :)

**Comment by yankejustin** [comment]
@MaxXor There is no problem, I just wanted to give lordcedrich and any others that may stumble upon this issue in the feature insight that this is actually not an issue, but rather is a social engineering trick. :)
