### ISSUE TITLE
More than one Client having the same User@PC

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#265]
As shown in the picture there are 2 Client having the same User@PC
so when I get keylog for example from one of them the server overwrite the other's logs
So we need to think about solution to solve this like : Short HWID (may be 6 chars long) so we can avoid this problem

------------------------------------------
![xr4](https://cloud.githubusercontent.com/assets/12255107/8000716/9e86987e-0b5e-11e5-819b-eb82ace3d5f7.png)

**Comment by MaxXor** [comment]
Each client already sends a unique ID, we can use this for example.

**Comment by DragonzMaster** [comment]
OK, That would be nice
We just need to make the created folder for each client ended with Uniqe ID
For ex: User@PC_E5F2A

**Comment by DragonzMaster** [comment]
Sorry I forget to ask you if is it possible to replace the IP with (User@PC) in the Client Forms title [File Manger, Startup Manger ....] ?? @MaxXor 
Excuse me if you find my English bad :)

**Comment by yankejustin** [comment]
Your English is fine, DragonzMaster. :)

**Comment by yankejustin** [comment]
Is it not possible for different clients to have the same local domain name?

**Comment by DragonzMaster** [comment]
@MaxXor : Is the Unique ID that Client send is changeable ( I mean that if the client disconnect or restarted it will be changed ) ??
If not we can use it to name the client's folder (for ex ) like : User@PC_UniqueID
@yankejustin : Thanks :)

**Comment by MaxXor** [comment]
Yes it is, will be changed.

**Comment by DragonzMaster** [comment]
Thanks @MaxXor
