### ISSUE TITLE
Client does not work on MaxXor/dev-buffer

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#266]
<h1>Issue:</h1>
The built client on the <code>MaxXor/dev-buffer</code> branch does not function. It states that the application has crashed (Windows' message says the program has stopped working). I have no details on this yet but it renders the built clients useless...
<h1>Notes</h1>
I am able to the client functioning in the <code>DEBUG</code> configuration. The <code>RELEASE</code> configuration will not work for me.
<h1>Additional Information</h1>
- Running on a Windows 7 machine
- Local connection

**Comment by yankejustin** [comment]
d3agle fixed the issue. :)

**Comment by yankejustin** [comment]
I am still having this problem. Hmmm. Would someone possibly be able to tell me if they're working using the <code>MaxXor/dev-buffer</code> branch please? My clients simply <b>will not</b> function. They crash about two seconds after starting them.

**Comment by MaxXor** [comment]
Yea, the renaming is the reason. I need to exclude more namespaces, damn.

**Comment by MaxXor** [comment]
Fixed it now finally.

**Comment by yankejustin** [comment]
Thank you. I didn't even catch that first mistake! x)

**Comment by MaxXor** [comment]
Same for me. :dart:

**Comment by yankejustin** [comment]
Is it working for you now? My clients are half-connected but aren't showing up on the <code>ListView</code>.

**Comment by MaxXor** [comment]
Can you better explain what you mean with half-connected? :)

**Comment by yankejustin** [comment]
I was debugging and saw the client in the <code>_clients</code> list (where we hold all of our clients), and I saw it tries to disconnect them (throwing an <code>ObjectDisposedException</code> that was caught but still showed up) on the amount of clients I tried to connect... 
It seems almost if they're not entirely connected, though, because they don't show up in some spots like the GUI.
