### ISSUE TITLE
Is it possible to run bat files?

### ISSUE THREAD

**Issue by lordcedrich** [MaxXor/xRAT#267]
On upload and execute, Is it possible to upload and execute a bat files and not only a .exe file on remote target pc?

**Comment by MaxXor** [comment]
I'm sure we can add this.

**Comment by lordcedrich** [comment]
This kind of function will be included on the next release?

**Comment by MaxXor** [comment]
No, sorry. I've added it to the Goals of RELEASE5.

**Comment by tidusjar** [comment]
@lordcedrich this has now been developed and is in RELEASE5
