### ISSUE TITLE
Remote Shell Issue

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#270]
<h1>Problem</h1>
The Remote Shell error output is currently not functioning. I am receiving the standard output contents of the Remote Shell and it is correctly being used by the server, but for some reason the error output is not seen on the Remote Shell.
<h1>Notes</h1>
Since the standard output is being sent and correctly used by the server, it is likely an issue with the client's way of gathering the error output stream. It is likely from a change after I re-wrote some of it, because it functioned after my changes. It could also (unlikely) be in the way the server handles the response of the message. I would assume it is the client since the server still receives and uses the standard output of the client's shell.
<h1>Additional Information</h1>
<b>1. System</b>
- Windows 7 (64-bit)

<b>2. Client</b>
- Default settings except for administrator privileges (enabled) and keylogger (enabled)

<b>3. Server</b>
- Built on <code>RELEASE</code> mode

**Comment by MaxXor** [comment]
Working fine now. :)
![RemoteShell stderror](https://i.imgur.com/Jg6SEGO.png)

**Comment by yankejustin** [comment]
Great. Thank you! :)
