### ISSUE TITLE
Client not responding

### ISSUE THREAD

**Issue by werkamsus** [MaxXor/xRAT#272]
If you try to either click multiple times in Remote Desktop, or keep Remote Desktop + Task Manager open at the same time, the client won't respond anymore. Although the process is still open and it is running the while (_connected) { Application.DoEvents(); Thread.Sleep(2500); } loop in Program.cs .

I've been trying to find a way to prevent this, but haven't come up with a solution yet.

Help would be very much appreciated :)

**Comment by MaxXor** [comment]
Seems like the client can not receive messages anymore then. I'll look into this.

**Comment by werkamsus** [comment]
Yeah, it seems as if it just stops to respond to anything if you send too many / different packets in quick succession

**Comment by MaxXor** [comment]
I think this should be fixed now, the File Manager bug too. :)

Can you confirm with the latest commits?

**Comment by werkamsus** [comment]
Can confirm that the bug is fixed locally, have to wait for a friend to assist me in order to confirm it to be working in a real environment.

Thanks for the fix! :)
