### ISSUE TITLE
File Manager Disconnected

### ISSUE THREAD

**Issue by AlienHack** [MaxXor/xRAT#275]
Hello, I have an issue when trying to download file larger than approximately 1-2 MB using the yesterday build.

When downloading file(large and small) with local machine, the file manager work just fine, but if i'm trying to download file (1MB ++ ) from remote PC, the connection was lost and disappeared then it reappeared after a while.

**Comment by AlienHack** [comment]
![screenshot_5](https://cloud.githubusercontent.com/assets/8213866/8611329/9f575a26-26e9-11e5-9859-ea61cac84edd.png)

**Comment by MaxXor** [comment]
Thanks, I can reproduce this and already partly fixed it. Now it seems only to disconnect when the file is over 300MB. I will push the commits soon.

**Comment by xDESTROYx** [comment]
same problem.

**Comment by MaxXor** [comment]
Will be fixed today. :)

**Comment by MaxXor** [comment]
Can you test if the bug is fixed for files < 400MB?

**Comment by AlienHack** [comment]
Okay, will test and gonna report it here

**Comment by yankejustin** [comment]
@MaxXor Have you found the reason it was not initially working, or was the logic for networking just flawed in this area?

**Comment by yankejustin** [comment]
I now have some free time again, and I would certainly not mind cleaning up this area before going back to the Registry Editor!

**Comment by MaxXor** [comment]
@yankejustin The networking was the problem here. You can work on the registry editor, I'll do this here. :)

**Comment by yankejustin** [comment]
Got it. I have a request since I have to go to work for a while: would you mind helping me fix some conflicts from all of the commits since I last was able to work on the Registry Editor and submit a PR to that branch? It would help very much. :)
Thank you!

**Comment by AlienHack** [comment]
I've tried download 120 MB file, it's working fine. I think this commit resolved the problem.

**Comment by MaxXor** [comment]
@AlienHack Nice to hear that it's working! Thanks.
