### ISSUE TITLE
The new release of old bot stop working ?

### ISSUE THREAD

**Issue by xDESTROYx** [MaxXor/xRAT#278]

**Comment by xDESTROYx** [comment]
translate google.

**Comment by yankejustin** [comment]
What is your native language? Perhaps one of us speaks it. I am not entirely sure what is being asked.

**Comment by MaxXor** [comment]
I'm going to release a small bugfix-update because I think the latest release at the moment contains some serious bugs in the networking code.

**Comment by xDESTROYx** [comment]
yankejustin, language russian.

**Comment by xDESTROYx** [comment]
MaxXor, thanks.

**Comment by MaxXor** [comment]
No problem. If you haven't already, you can download the latest release here: https://github.com/MaxXor/xRAT/releases

**Comment by xDESTROYx** [comment]
MaxXor, Do not connect the bots from RELEASE 4 (

**Comment by MaxXor** [comment]
Take a look at these update instructions: https://github.com/MaxXor/xRAT/wiki/Updating-a-Client

**Comment by xDESTROYx** [comment]
It turns out for each version is required to build new ?

Old client may persist for several years. Connect going to each release and update silly.

**Comment by MaxXor** [comment]
Yes a new build of the client is required for an update.

I've wrote in the code that I don't like this way of updating, but it works...
https://github.com/MaxXor/xRAT/blob/96c358b12a44d825050dfa76a63f18eb6cb8908c/Client/Core/Commands/ConnectionHandler.cs#L25
