### ISSUE TITLE
Linux support for the Server

### ISSUE THREAD

**Issue by gngeorgiev** [MaxXor/xRAT#279]
How about we make it possible run the server on a linux machine(Ubuntu, Arch, etc.). This will allow the RAT to have a bigger audience. I can do this if you see fit.

**Comment by MaxXor** [comment]
Have you already tried running it with Mono, does it work, are there errors?

**Comment by gngeorgiev** [comment]
Yeah, there are `NATUPNPLib` does not work and the theming. Other things should be minor.

**Comment by MaxXor** [comment]
Ah, alright. Yes the Listview calls some windows-only functions... maybe we could use an alternative to NATUPNPLib to have support for UPnP on Linux too.

**Comment by gngeorgiev** [comment]
Yeah, I think we can use https://github.com/lontivero/Open.NAT. As it will work on bot windows and linux since NATUPNPLib is a COM library which can in no way be used in Linux.

**Comment by MaxXor** [comment]
Alright, I'll make the library change later today so we can get rid of the COM library.

**Comment by gngeorgiev** [comment]
Refer the PR here so I can test it out :star2:

**Comment by MaxXor** [comment]
Sure!

**Comment by MaxXor** [comment]
Added it. :)

**Comment by gngeorgiev** [comment]
Great, gonna test it out sometime tonight probably.

**Comment by MaxXor** [comment]
Thanks! I've tested it on Windows, worked very well.

**Comment by yankejustin** [comment]
@MaxXor I would imagine that the Keylogger will be very broken since it relies on Windows' Hooks.

**Comment by MaxXor** [comment]
@yankejustin We are talking here about the Server only. :)

**Comment by yankejustin** [comment]
Oh, right. I apologize. :)

**Comment by MaxXor** [comment]
Now it's starting on Linux with Mono, gonna check the Builder too later.

**Comment by bitterypaul** [comment]
Will the remote desktop work on linux

**Comment by d3agle** [comment]
Remote Desktop currently as it is won't work on linux.  We would just need to disallow the hooks that the keyboard input uses for it to work.

**Comment by MaxXor** [comment]
Yes, Remote Desktop should be disabled on Mono to prevent any crashes.

**Comment by d3agle** [comment]
I'm currently working on keyboard input for Remote Desktop through Mono

**Comment by MaxXor** [comment]
You don't need to do that, it's still incompatible with the entire UnsafeStreamCodec. ;)

**Comment by d3agle** [comment]
It is working for me on Ubuntu 14.04 :D, Mono JIT compiler version 4.0.3 (Stable 4.0.3.19)

**Comment by MaxXor** [comment]
Oh, you are right, only the encoding uses functions (i.e. `memcpy`) from the `msvcrt.dll`. Decoding in the server is fine. :+1:

**Comment by d3agle** [comment]
Everything seems to work fine, from what I've tested on the Server with Mono.. I think using the .NET events for the picturebox (e.g. OnKeyDown) might be the best way to support keyboard input.  Do you think this would be fine?  If so, I can start working on it!

**Comment by MaxXor** [comment]
Yes, you can easily change this I guess.

**Comment by d3agle** [comment]
Right, I believe if we were to implement the mouse wheel we would have to use a parent control to access the MouseWheel event.

**Comment by d3agle** [comment]
Could anyone with a linux host machine test the functionality of keyboard input from the `master` branch located here: https://github.com/d3agle/xRAT ?  

Unfortunately I can't test this, as I don't have any linux machines to test on.  Running linux from a VM testing this won't work because my host loses focus.
