### ISSUE TITLE
UPnP not working with D-Link router

### ISSUE THREAD

**Issue by itapi** [MaxXor/xRAT#280]
hi. first of all i would like to say your work is awesome.
but im trying to connect from computer in other network(not on lan) i entered my external ip instead of "localhost" and checked the "try to auto port forward" option. but it doesnt works. seems like nothing happend. i would apperciate any help. my firewall is turned off and no antivirus or somthing.

**Comment by MaxXor** [comment]
You have to turn the option on and then start listening again (means you have to stop once when it's already listening).

**Comment by itapi** [comment]
@MaxXor  yep. tried also this. is it working for you? o.O

**Comment by MaxXor** [comment]
Yes, I'm using an AVM Fritz!Box 7360 router. Can you check if your router supports UPnP and has it enabled?

**Comment by itapi** [comment]
@MaxXor  seems like it support it and enabled too.
![image](https://cloud.githubusercontent.com/assets/10478457/8765117/0fb3f3d2-2e07-11e5-937c-ed950272727f.png)

**Comment by MaxXor** [comment]
Can you place a breakpoint [here!](https://github.com/MaxXor/xRAT/blob/master/Server/Core/Helper/UPnP.cs#L44) and tell me if it finds a device?

**Comment by itapi** [comment]
@MaxXor  allright in a second

**Comment by itapi** [comment]
@MaxXor  it does work. it find the device

**Comment by MaxXor** [comment]
Okay, thats good. Now I would need the response from your UPnP device. Can you capture the UPnP packets with your favorite network sniffer for me?

**Comment by MaxXor** [comment]
I know it's not that easy, maybe you can use smartsniff or wireshark to capture this. Or could you try it with another router, if you have a spare one.

**Comment by d3agle** [comment]
This is happening to me as well.  When I start the server, I check the 'Enable UPnP' in the settings and start listening, but UPnP doesn't work off the initial start of listening.  I have to stop listening and then start listening again for UPnP to work.

**Comment by MaxXor** [comment]
@d3agle but this is another issue, for you it's at least working. For @itapi not.
Yours is easy to fix, I'll just need to activate the UPnP module when you check the "Enable UPnP" checkbox.

**Comment by d3agle** [comment]
Oh right, I misunderstood.  Sounds good!
