### ISSUE TITLE
File Manager Ideas

### ISSUE THREAD

**Issue by alpha-supporter** [MaxXor/xRAT#284]
- would be great to see the download speed in kb/s
- is there any other way to show the diffrent drives? dropdown is not my favorite for this - you cant image if the drive is an HDD, CD or Network-Drive
- i think you need to limit the maximum simultaneous file downloads - looks crazy when you select 20 or more files for download
- cant remove downloaded items from the "transfer" window

**Comment by MaxXor** [comment]
Added all your ideas to #262.

Hehe, yea i tried this too with over 100 files just for fun (stability test). Gonna give this a maximum.
