### ISSUE TITLE
Remote Desktop crashes when changing screen resolution

### ISSUE THREAD

**Issue by MaxXor** [MaxXor/xRAT#292]
Remote Desktop is crashing the server if client changes resolution while its running. This happens after stopping and then starting again the Remote Desktop.

**Comment by MaxXor** [comment]
@d3agle Can you confirm this is fixed for you?

**Comment by d3agle** [comment]
Confirmed working! :)

**Comment by MaxXor** [comment]
Great! Thanks for testing again. .)
