### ISSUE TITLE
Remote Desktop Performance Improvement

### ISSUE THREAD

**Issue by itapi** [MaxXor/xRAT#294]
Hey maor,i glanced over your remote dekstop code and it seems awesome, i liked the way you used to optimize the performances by dividing it into blocks and sending only the differences, but i've also seen you're using the regualr screnshot method which is slow as hell and also use more cpu. i'll just suggest to use use the gdi method to get it working way fast  have a look here:
http://www.c-sharpcorner.com/uploadfile/perrylee/screencapture11142005234547pm/screencapture.aspx
its simple and fast. 
by the way im the one who asked about the upnp a week ago.. haha i wasnt home so i couldnt actualy answer but i'll download wireshark and i'll check it..
one last thing.
you're name... aren't you from israel? :smile:

**Comment by MaxXor** [comment]
Thanks, I've changed it.

No I'm not from israel.^^
