### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by DavesPlanet** [MaxXor/xRAT#31]
The original connection issue I had with not being able to get through my modem/router appeared to work temporarily but it was a fluke. I can set port forward to work with P2P, and CanYouSeeMe.org can see my connection, but no inbound connections succeed.

I got around this by using the proXPN vpn, a great vpn with free option that works nicely with xRat - as long as the server and client are running on the same machine. The connection goes through the proxy and everything plays nice with both pieces of software on my local machine, but as soon as I try to go between two machines the server software goes from "listening: True" to "listening: False" the moment the incoming connection arrives. I can prove it by leaving the server up as long as I like and it will continue to listen for a connection, but as soon as I bring up a client on a second machine the server stops listening.

Current code pulled 14 days ago, compiled with 2010 express, tested between an XP laptop and a Vista desktop in both directions with the same results.

**Comment by MaxXor** [comment]
Can you send me an example of a built client? I'll check this.
Build it with your settings. :)

**Comment by yankejustin** [comment]
What version of the .NET framework are you building with? Are you seeing any exceptions in the 'Output' window?
By the way, Visual Studio's newer versions also have a free Express edition. Perhaps your system is unable to use them, but I just wanted to throw that out there.
