### ISSUE TITLE
Remote Desktop - not able to take on another machine

### ISSUE THREAD

**Issue by bhalajisw** [MaxXor/xRAT#314]
hi,
I can take remote desktop or control only if the server code is running on a host. No support to run the server code on another client and perform RAT operations.

**Comment by d3agle** [comment]
@bhalajisw When you say running the Server on another client, are you talking about on a Virtual Machine?

**Comment by d3agle** [comment]
@bhalajisw Also, could you elaborate a little more about the issue you are having?  More specific information such as 'Keyboard input isn't working' or 'The screen capturing isn't working'.

**Comment by bhalajisw** [comment]
Hi,
I want server code to be able to run on any machine. Client connects to host. But i can connect all clients only when i run server app on that host alone. Server code should have flexibiluty to run and take remote desktop anywhere. Eg. Like teamviewer.

**Comment by d3agle** [comment]
Set up a DNS https://freedns.afraid.org/ and point it towards your IP address

**Comment by bhalajisw** [comment]
Hi d3agle,

This is my scenario - I want that client app to be run on several clients pointing to a server. Server app should be able to run on any client application and connect the remote machines.

Running Server application on any machine not only on the host machine.

A more simple is i want this remote desktop to be used like teamviewer like anywhere conecting.

**Comment by MaxXor** [comment]
xRAT doesn't work like this. The Server is meant to be run on a stationary host, which acts as a controller for the Clients. Just use a dynamic DNS service and point your domain to other machines if you want to switch the host.
