### ISSUE TITLE
Visit a Website Feature Addition

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#32]
I have written a program that very quickly sends packets to a specified destination quite efficiently. I noticed that the "Visit a Website" feature only sends a single requests. Perhaps there could be a few extra options added to the GUI that would allow continuous sending of packets to a destination. I have the code to provide from a project I was messing with and ready to implement, but I was wondering if this is a feature you would like to be added.

**Comment by MaxXor** [comment]
Thanks, but I think the "Visit a Website" feature is ok as it is now.

**Comment by OpenSourceCS** [comment]
Add DDoS support
