### ISSUE TITLE
Any other features that will be added in the future?

### ISSUE THREAD

**Issue by blackfox1337** [MaxXor/xRAT#320]
I'm just interested to know if anything like sound capture or video capture will be added :)

**Comment by yankejustin** [comment]
I am confused... We already have video capture..

**Comment by yankejustin** [comment]
Actually, what do you mean video capture and sound capture? Capture of what?

**Comment by blackfox1337** [comment]
Video capture as in being able to see the other persons video camera feed and for sound capture basically being able to access their mic.

**Comment by blackfox1337** [comment]
Ahh i found the answer :) Dont worry
