### ISSUE TITLE
client can work on net 2.0

### ISSUE THREAD

**Issue by AlexNowhere** [MaxXor/xRAT#325]
if you interesting client whith some fixes can work on not 2.0
at first change solution properties to net.2.0)))
 install linqbridge (https://bitbucket.org/raboof/linqbridge) by nuget for client solution.
it`s dll add linq support to net2.0 nothing to fix in code)))
after it install json.net(newtown) and fix JsonUtil.cs to this code:
using System.IO;
using System.Text;
using Newtonsoft.Json;

namespace xClient.Core.Recovery.Utilities
{
    public static class JsonUtil
    {
        public static string Serialize<T>(T o)
        {

            return JsonConvert.SerializeObject(o);
        }

        public static T Deserialize<T>(string json)
        {
            return JsonConvert.DeserializeObject<T>(json);
        }
    }
}

ps all depencies install from nuget.
now client can work on ald windows xp machines)

**Comment by MaxXor** [comment]
No downgrade .NET Framework 2.0.
