### ISSUE TITLE
Server crash when trying to build a Client without Client.bin

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#52]
Reproducing:

1) Clean solution
2) Press the start button (just build and run the Server).
3) Try to build a Client (will crash).

Why?:

The top of the 'Build' method (that builds the Client) loads the Client's built .bin file into a variable, but fails to take into account the chance that it is not there or is unusable.

I have marked this as an issue because, while it is something the server can't do much about (we need that .bin file!), the server should not crash just for trying to build a Client.

Where?:

https://github.com/MaxXor/xRAT/tree/master/Server/Core/Build/ClientBuilder.cs#L15

Solution:

I just wanted to bring this to your attention and let you handle it. To solve this issue, just enclose the variable in its own try-catch. That way, it will still fail, but we will not crash and burn.   :)

Note: I personally suggest it has its own try-catch block so that you can give a special Exception message that states something like: "Unable to load the Client Assembly Information. Please re-build the Client."

**Comment by MaxXor** [comment]
Thanks!
