### ISSUE TITLE
Formatting throughout program

### ISSUE THREAD

**Issue by d3agle** [MaxXor/xRAT#53]
There seems to be alot of classes that have spaces and alot of classes that tabbing.

This causes alot of inconsistencies when trying to push commits.  Could you perform a Format code to all documents?

I believe this can be done by highlighting all the class files throughout the program and hitting Ctrl + K + D

**Comment by yankejustin** [comment]
I just tend to fix it as I work on different classes. Auto-format tends to screw up sometimes.

**Comment by MaxXor** [comment]
Hey,
I'll try to fix it and replace the tabs with 4 spaces.

Sorry for the late response.

**Comment by d3agle** [comment]
Thanks!
