### ISSUE TITLE
ERROR CODE: 10013

### ISSUE THREAD

**Issue by Johnwick101** [MaxXor/xRAT#651]
My rat wont connect, its showing the below error message.
"An unexpected socket error occurred: An attempt was made to access a socket in a way forbidden by its access permissions."

Kindly assist

**Comment by BackfireRAT** [comment]
You might have another program listening on the requested socket. use the command prompt with the command "netstat -ano | findstr "*YourPortHere*"" and replace *YourPortHere* with the port you are trying to use. If you get results back, you can kill them by "taskkill /f /pid *number*" and replace *number* with the number at the end of the result from netstat.
