### ISSUE TITLE
Possible Cross-Thread

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#66]
Fix soon
https://github.com/MaxXor/xRAT/blame/6228b5fc8f0e10bda7de361fc0e0c6300a9e185c/Server/Forms/FrmMain.cs#L506

**Comment by yankejustin** [comment]
Oops, meant to make this issue in my fork... Aw well. Worth taking a look into!   :)

**Comment by MaxXor** [comment]
No problem, I'll fix this right now.
