### ISSUE TITLE
Feature Request: Reverse Connection for servers behind a Router or a Firewall

### ISSUE THREAD

**Issue by vigneshkarthisan** [MaxXor/xRAT#71]
Could anyone please add Reverse Connection functionality. xRAT is the best Remote Access Tool I have ever seen. Reverse Connection is useful when a server is unreachable if it is behind a router without UPnP and port forwarding is impossible. Servers can be deployed without port forwarding the routers if Reverse Connection is enabled. Reverse Connection as a separate feature (or as a opt-in feature) is like being in heaven. It allows for unattended Server installations

**Comment by yankejustin** [comment]
I like this idea! :)

**Comment by yankejustin** [comment]
By the way:
1) What would be the suggested way to obtain the users' ip?
2) How many of xRAT's features would not be possible in a reversed connection?

**Comment by vigneshkarthisan** [comment]
Perhaps making the client to send the current IP address as a text log in a FTP server or something like that.

**Comment by yankejustin** [comment]
@MaxXor This can be closed.

**Comment by rabbitsmith** [comment]
why
