### ISSUE TITLE
File Manager issue

### ISSUE THREAD

**Issue by Krytox** [MaxXor/xRAT#75]
Apparently, the files with the size over 2mb cannot be downloaded the window just closes and client reconnects.

**Comment by yankejustin** [comment]
The issue is not always capped at 2mb. After messing with this issue a bit, I believe the largest file I have been able to successfully download was ~8.5mb.

**Comment by yankejustin** [comment]
Also, for those interested in helping us fix this issue, there is an "InvalidOperationException" being thrown somewhere. That is the likely cause of the inability to download medium-large files...

**Comment by MaxXor** [comment]
The client/server can transfer max. 2MB at once. Each file was split into parts of 2MB - 5 Bytes, this is too little. After encrypting the the part of the file, it can be over 2MB (happens for already compressed files like mp3 or zip/rar-archives). This will make the client loose the connection and then reconnect, the server receives an invalid packet.
