### ISSUE TITLE
Suggested key for Keylogger

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#79]
Perhaps we should add the 'Control' key to the Keylogger. Looking back at logs I have generated on myself, it is just a bit strange to see things like:
zzzzzzzzzzzzyyyyyyzzzzzzzzzzzzz

**Comment by d3agle** [comment]
I agree. Also, perhaps it would viable to include the Windows key as well?  For example, opening a run dialog [Win] + R would look clean in the logs, as well as the Control key [Ctrl] + S.

**Comment by MaxXor** [comment]
Great idea, anyone wants to add this? :)

**Comment by d3agle** [comment]
I'll add it.  I'll push a commit when i've made the changes, but I'd like to fix another issue as well so I will add them around the same time.

**Comment by ShittyAdvice** [comment]
@d3agle Hey while you're at it something I noticed:
Some special keys that print / show after pressing another key like:  `^ " '`  don't properly work when having the RAT running. Since you're working on the keylogger right now maybe you could look into that as well

**Comment by d3agle** [comment]
@ShittyAdvice, could you give me an example of what is happening?  I'm having a hard time understanding how you mean

**Comment by DragonzMaster** [comment]
i have just tried the keylogger
and seems to do its work as it should to be

**Comment by ShittyAdvice** [comment]
@d3agle
Might be just a problem at my side but the keys like `^ " '` don't work.
Also sometimes a big lag in typing. But I suppose that is when it's sending the data or something

**Comment by yankejustin** [comment]
What type of keyboard are you using? What version of Windows?

**Comment by ShittyAdvice** [comment]
@yankejustin
Windows 8.1 Pro
Mechanical Keyboard with INTL
