### ISSUE TITLE
How to Change client process name ? 

### ISSUE THREAD

**Issue by h0ay** [MaxXor/xRAT#835]
When i run the client , it shows quasar client in the task manager ,how to change it to any name we wish ?

**Comment by MaxXor** [comment]
Please confirm that you are using the release configuration of Quasar and then use the included client builder to choose the filename on the installation tab. The filename equals the process name once run.

See here for more information: https://github.com/quasar/Quasar/wiki/Client-deployment-settings#installation-location

**Comment by h0ay** [comment]
https://ibb.co/WD7NYFs
https://ibb.co/HTXhKBh

**Comment by MaxXor** [comment]
Ah, you mean this tool tip, well that can not be changed currently. If you want to hide the icon in the taskbar enable the unattended mode when building the client.

**Comment by h0ay** [comment]
Okay
