### ISSUE TITLE
File Manager Form Enhancement

### ISSUE THREAD

**Issue by vigneshkarthisan** [MaxXor/xRAT#84]
A button or a right click feature in File Manager opening a RemoteShell window cd-ing to the present directory in the File Manager window same as the Open in command prompt in File Explorer of windows will be useful. This may be one step forward to a complete File Manager.

Features to Eject a Removable Drive, changing attributes of files would be awesome

**Comment by d3agle** [comment]
Awesome idea!

**Comment by yankejustin** [comment]
Agreed. With the shiny new features, better navigation and integration of the features is now more necessary.

**Comment by vigneshkarthisan** [comment]
Formatting a drive (directly from the File Manager instead of using the  ```format``` command from Remote Shell) is also missing.

**Comment by yankejustin** [comment]
I'd just like to suggest that we should leave it like that. If someone that knows less about using this program sees that option and doesn't truly understand it, the potential for a costly and frustrating accident would be high.
On the other hand, maybe it would probably be a good feature as a menu item. Under an "Advanced" tab or something to that effect.

**Comment by vigneshkarthisan** [comment]
It would be better if it asks confirmation before executing dangerous tasks like formatting, similar to how GitHub asks to type the name of the repo before deleting it.

**Comment by vigneshkarthisan** [comment]
Thanks for implementing.

**Comment by vigneshkarthisan** [comment]
Enhancements

- [x] Open in Remote Shell
- [ ] Eject a Drive
- [ ] Change File / Folder attributes

Optional

- [ ] Format a drive
