### ISSUE TITLE
File Manager Form "File not found."

### ISSUE THREAD

**Issue by yankejustin** [MaxXor/xRAT#87]
When attempting to download a file that is in the root directory, it will not work. The status message in the downloads tab states that it was not found.
1) Find why it isn't working and fix the bug (of course).
2) Modify the catch clause - where it is "catch (IOException)" - and don't let it set all issues caused by IOExceptions write the status as "File Not Found." because there are other IOExceptions that can thrown by trying to download a file.

**Comment by MaxXor** [comment]
I tried putting xrat.exe to C:\ and downloaded it with the File Manager.

Did your file exist?

**Comment by vigneshkarthisan** [comment]
modify the catch clause into ```catch(FileNotFoundException)```

**Comment by yankejustin** [comment]
Hmmm... It seems that I didn't have the permission to read the file contents.

**Comment by MaxXor** [comment]
Can you confirm it's working with Administrator rights?

**Comment by yankejustin** [comment]
I need to research this a bit more. For now, I will close this because it seems to be functioning. There are so many things that could have caused the IOException, so I will open this once more if I find something unusual that was the fault of xRAT.
