### ISSUE TITLE
Open Containing Folder Addition to Transfers + Colorizing Window Title and adding time to keylogger

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#90]
*- I think it would be a good idea to add "Open Containing Folder" to files in transfers list or make it like "Total Commander" with 2 separate file windows 
*- adding Common DIRs like appdata- startup to quickly reach them (suggest to add them combobox)
*- another addition would make the Key log looks great (colorizing the window title and add the time at the end)

**Comment by OpenSourceCS** [comment]
Superb idea!. Y don't somebody implement it?

**Comment by yankejustin** [comment]
@OpenSourceCS The Keylogger is so new so it is somewhat basic of an interface. I am going to touch up on the interface and documentation tonight, but for now I am going to fix a multitude of issues and such. It is important to get things functional and bug-free before making it more usable.
I do agree, I like these ideas.
