### ISSUE TITLE
DDoS support?

### ISSUE THREAD

**Issue by OpenSourceCS** [MaxXor/xRAT#94]
Add DDoS support with forms to add new IPs or websites.

**Comment by yankejustin** [comment]
Similar question already answered by @MaxXor 
https://github.com/MaxXor/xRAT/issues/32
So I doubt this is desired.

**Comment by yankejustin** [comment]
I already have almost all of the code, but it is entirely the choice of the owner of this project.

**Comment by MaxXor** [comment]
DDoS support will not be added.
