### ISSUE TITLE
Compression Algorithm ??

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#97]
Is QuickLZ really the best choice as compression algorithm ??
as there is TWO more algorithms do a good job with compression
after i searched for sometime i found that there is Snappy (fastest between them) Algorithm and LZ4 (latest is very fast)
both of them do a great job and they faster (a bit) than QiuckLZ
you can find a comparison between them here :
http://encode.ru/threads/1266-In-memory-benchmark-with-fastest-LZSS-%28QuickLZ-Snappy%29-compressors

**Comment by OpenSourceCS** [comment]
Yes you are right. LZ4 is pretty good yet there is not yet a pure c# algorithm. there are only bindings.


Please see #96 #95 #94 #90 #85

**Comment by DragonzMaster** [comment]
as for LZ4 i found a library for .net projects
http://lz4net.codeplex.com/
@OpenSourceCS

**Comment by OpenSourceCS** [comment]
It is a binding project. It requires VC++ 2010 Redist. Moreover the native dll(whatever) of LZ4 (which is written in C) cannot be binded with Client.exe.

**Comment by OpenSourceCS** [comment]
QuickLZ implemented in xRAT is just a single file written in pure c#. It makes things simple.

**Comment by yankejustin** [comment]
Hmmm... I can port an algorithm if it is much better than what we currently use. Please know that the article mentioned is 4 years old. If possible, please show me a more recent bench mark and I will certainly convert it to C#.   :)

**Comment by DragonzMaster** [comment]
as for snappy it hasn't changed a lot and you can see here 
https://github.com/google/snappy/commit/eeead8dc38ea359f027fb6e89f345448e8e9d723
i might help you :)
-------
and i am trying to find newer benchmark for LZ4

**Comment by DragonzMaster** [comment]
GOOD News
Snappy (the extremely fast algorithm) is available in c# .net (4 years ago)
so you don't need to convert it ... here is the project  
https://github.com/Kintaro/SnappySharp

**Comment by OpenSourceCS** [comment]
need to benchmark snappy and quickLZ before implementing

**Comment by DragonzMaster** [comment]
i found more benchmarks i hope you find it useful
i want to mention that they are in different Implementation (java)
but it shows the difference between them and there performance
LZ4 shows to be the fastest :+1: 

reference : 
http://java-performance.info/performance-general-compression/
https://sites.google.com/site/powturbo/home/benchmark
https://code.google.com/p/lz4/
http://catchchallenger.first-world.info//wiki/Quick_Benchmark:_Gzip_vs_Bzip2_vs_LZMA_vs_XZ_vs_LZ4_vs_LZO

**Comment by OpenSourceCS** [comment]
does anyone find lags in network transmission?. I think QuickLZ is sufficient for now. But after implementing other features, we can come back to this. @MaxXor please start assigning people for specific issues. Thanks!

**Comment by yankejustin** [comment]
I have no issues with network transmission. ProtoBuf is actually very fast and efficient.

**Comment by MaxXor** [comment]
DragonHunter recommended that we should use QuickLZ instead of LZ4. I also think we should stick with it.

**Comment by yankejustin** [comment]
By that, you mean we should continue using what we currently use? I would just like to clarify.

**Comment by MaxXor** [comment]
Yes, correct. We'll change it when the current compression algorithm is not fast enough for our needs. But currently it is.

**Comment by yankejustin** [comment]
Okay, thank you for the clarification. I agree.

**Comment by electriclee** [comment]
useless lz4 | the quicklz is superee.
