### ISSUE TITLE
[CTRL+Shift+any letter] keylogging

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#98]
when trying to press ctrl+z (as an example) it is logged correctly
but when trying to press [CTRL+Shift+any letter] it don't log shift key but instead of that it capitalize the letter example : when i press [CTRL+Shift+z] it is logged [CTRL-Z]
and the same issue when i press [ALT+Shift+z] is logged [ALT-Z] - with the letter capitalized

**Comment by OpenSourceCS** [comment]
yes please implement this as well as some other keylogger improvements such as #95(Keylogger escape key).

**Comment by yankejustin** [comment]
Please try my fix and see if it resolves your problem.

**Comment by OpenSourceCS** [comment]
I have added a note in ur fix @yankejustin .Please check  #96 #95 #94 #90 #85

**Comment by yankejustin** [comment]
Please don't reference issues opened too much. It makes it confusing for me to resolve them (as I check to make sure nobody else is also working on it). I am trying to resolve them all. ;)

**Comment by yankejustin** [comment]
If someone could give me the OK for my changes, I will send the pull request in. Unfortunately can't check at this moment. :100:

**Comment by d3agle** [comment]
I'll check in a few minutes, nice code btw :)

**Comment by yankejustin** [comment]
Thank you very much. :)

**Comment by yankejustin** [comment]
I am devising a better way to fix this, but I will implement it later tonight after thinking it over more.

**Comment by OpenSourceCS** [comment]
would be nice if we add arrow keys.

Some people type their passwords one character back and forth. so implementing arrow keys might be useful.

VK_ codes are 37, 38, 39,40
Print Screen is 44.

**Comment by OpenSourceCS** [comment]
I think pressing shift and any letter(say l) for captializing it would result in [Shift + L].

**Comment by yankejustin** [comment]
@MaxXor If possible, please assign this to me.

**Comment by DragonzMaster** [comment]
the problem shoud be solved by checking if the ctrl or alt pressed + shift so the shift key should be logged else (shift + any letter) shoud capitalize the letter only and don't log shift key

**Comment by electriclee** [comment]
superi please do it.

**Comment by yankejustin** [comment]
Hello all!
I have made many updates. It won't be functional until tomorrow, but I would love it if I got some help adding some attributes for the KeyloggerKeys :)
https://github.com/yankejustin/xRAT

**Comment by d3agle** [comment]
@yankejustin, Good work.  I've pushed a commit to your branch with some additional attributes.  I didn't add attribute members for all of the keys, only the ones I felt were necessary.

**Comment by yankejustin** [comment]
@d3agle Thank you! Just be sure to make the other parameter (the optional one) true so it will highlight special keys like function keys.
Example:
Instead of logging
f1
It would log
[f1]
with the highlights. :)
The attribute would be [KeyloggerKey("F1", true)]

**Comment by yankejustin** [comment]
@d3agle Thank you for the contribution. :+1:

**Comment by d3agle** [comment]
No problem and sorry I forgot to add those, just pushed a commit

**Comment by DragonzMaster** [comment]
good work guys @yankejustin @d3agle 
both of you made great efforts thnx

**Comment by yankejustin** [comment]
@MaxXor This one can be closed because it is no longer an issue in the new branch. :)
