### ISSUE TITLE
KeyLogger arrow keys

### ISSUE THREAD

**Issue by OpenSourceCS** [MaxXor/xRAT#99]
Some people type their passwords one character back and forth. so implementing arrow keys might be useful.

VK_ codes are 37, 38, 39,40
Print Screen is 44.

**Comment by yankejustin** [comment]
@MaxXor If possible, please assign this to me.

**Comment by electriclee** [comment]
wastee if guys play games if keylogger is runnin | disable keylogge if game is runnin[i.e full screen applic
